### ISSUE TITLE
patch to Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by hdatma** [mozilla/http-observatory#106]
**http-observatory/httpobs/scanner/analyzer/misc.py**

```
+# http://www.w3.org/TR/access-control/#access-control-allow-origin-response-header
+ if 'null' in domains:
+          output['result'] = 'cross-origin-resource-sharing-is-null'
+
if '*' in domains:
            output['result'] = 'cross-origin-resource-sharing-implemented-with-universal-access'
```

**http-observatory/httpobs/scanner/grader/grade.py**

```
# Cross-origin resource sharing
+
+# http://www.w3.org/TR/access-control/#access-control-allow-origin-response-header
+'cross-origin-resource-sharing-is-null': {
+  'description': 'Content is not visible via cross-origin resource sharing (CORS) files or headers',
+  'modifier': +5,
+},
```

**Comment by marumari** [comment]
I'm not sure what the patch is?  Can you send a PR and describe what it's doing?  Thanks!

**Comment by hdatma** [comment]
https://github.com/mozilla/http-observatory-website/issues/5

**Comment by hdatma** [comment]
Since you are in Mozilla's security lab, would you please ask your supervisor to please ask their own supervisor to please put someone in charge of writing a comprehensive configuration script for the ESR source code? 

You see, one thing is to *say* that you care about user's privacy and security, and another is to inject FF-ESR with half-baked and privacy-eroding code. The configuration script ought to opt-out (avoid compiling and be clear of) technologies like the following: 

datareporting, toolkit.telemetry, browser.tabs.crashReporting, toolkit.crashreporter, identity.fxaccounts, services.sync, social, browser.safebrowsing, browser.pocket, pdfjs, media.webspeech, media.webaudio, media.peerconnection, loop, experiments, network.allow-experiments, dom.vibrator (on desktop!), browser.search.geoSpecificDefaults, browser.search.geoip, geo.enabled, geo.wifi, dom.gamepad, camera.control.face_detection.enabled, browser.chrome.favicons, browser.chrome.site_icons, network.prefetch-next, dom.vr, webgl, gfx.font_rendering.graphite, browser.snippets, gfx.downloadable_fonts, browser.newtabpage, and device.sensors. 

Thank you.
