### ISSUE TITLE
Check for Referrer Policy

### ISSUE THREAD

**Issue by estark37** [mozilla/http-observatory#107]
As discussed on Twitter (https://twitter.com/estark37/status/770875377682001920), it would be cool if the observatory checked for the presence of Referrer Policy.

`<meta name="referrer">` is widely supported already. The observatory could also check for the `Referrer-Policy` HTTP header, though it's not shipped in any browser yet.

There were a couple idea for how to score referrer policies: you could simply make it a bonus for having it but no penalty for not having it (like HPKP); or you could give a penalty for a policy of `unsafe-url` and a bonus for having any other policy; or you could choose a reasonable baseline policy like `origin-when-cross-origin` and penalize for anything less restrictive than that.

But basically I think the important thing is to mention Referrer Policy at all regardless of the actual scoring, because I suspect many devs don't know it exists.

**Comment by marumari** [comment]
Thanks for submitting this, @estark37.  I've got some higher priority bugs to take care of first, but this is right up there and so I hope to take a look at it in the next month or so.  :)

**Comment by Elchi3** [comment]
Was about to file this issue :) Basic support [ships in Firefox 50](https://bugzilla.mozilla.org/show_bug.cgi?id=1264164), full support expected in Firefox 52 ([landed today](https://bugzilla.mozilla.org/show_bug.cgi?id=1276836)). 
I wrote some docs about this here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by marumari** [comment]
This is something I hope to tackle in Q4.  :)

**Comment by floatingatoll** [comment]
@marumari Anything else to do here after #152 and #155?

**Comment by marumari** [comment]
Nope, I think this is done!
