### ISSUE TITLE
no progress on Retrieving the Google HSTS Preload list

### ISSUE THREAD

**Issue by moustafak** [mozilla/http-observatory#114]
I am trying to start the scanner using this command:
`HTTPOBS_DATABASE_USER="httpobsscanner" HTTPOBS_DATABASE_PASS="password" /opt/http-observatory/httpobs/scripts/httpobs-scan-worker`

Initially I got this error 

> python3: can't open file 'httpobs/scanner/main.py': [Errno 2] No such file or directory

I updated the file `httpobs-scan-worker` to have it reference the full path to main.py, like so:
`python3 /opt/http-observatory/httpobs/scanner/main.py`

On second attempt to start the scanner, the above error went away but now I am getting stuck on the screen - it never times out but i waited long enough with no progress - same result on ubuntu 15.10 and 16.04 (vmware images).

> Retrieving the Google HSTS Preload list
> Retrieving the Google HSTS Preload list

However, I am able to read the chromium link directly from python cli:

```
>>> import requests
>>> requests.get('https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json')
<Response [200]>
```

I am now stuck without direction and spent hours to get this far.. any assistance to get me passed this would be much appreciated.

**Comment by unknownboy** [comment]
May be linked to #89 ?

**Comment by moustafak** [comment]
I don't think it was the same issue as you appear to be on a proxy and I am not. Perhaps @marumari can confirm but my main issue was I was expecting feedback after executing the scanner command whereas it may not actually be printing anything back to the user.

One thing I did notice is even though there is no feedback when launching the scanner, the Google HSTS list is retrieved.. i actually traced the python code line by line printing dummy data as a helper and noticed i was able to print the decoded Google HSTS data which to me indicates the json file was downloaded and parsed as well.

I think maybe you should check the postgres and scanner logs for clues and at least make sure the postgres user is getting authorized.

**Comment by marumari** [comment]
I made a recent update (0141086002c97c93d7493f1de403c3fd94eb3b14) that should hopefully be more clear on what's happening.  My guess is that things are working perfectly and it just isn't indicating because there's no real output from that process.

**Comment by moustafak** [comment]
Hi April.

Welcome back ☺

Thanks for the changes. This has helps avoid any confusion and now displays the message “Successfully downloaded and parsed the Chromium HSTS preload list”

Regards,
Moustafa

**Comment by marumari** [comment]
Sorry, I just noticed this one again!  I've been so busy!  Did you ever get it figured out?
