### ISSUE TITLE
Session cookie set without the Secure flag

### ISSUE THREAD

**Issue by jasin755** [mozilla/http-observatory#117]
Observatory reported my session cookie as unsecure. But it is. Website: https://www.byrko.cz

**Comment by marumari** [comment]
That's a strange one, looks like a bug of some sort.  I'm out of town next week, but I'll take a look at this as soon as I can.  Thanks!

**Comment by jasin755** [comment]
Ok. Thanks

**Comment by marumari** [comment]
So I get:

nette-browser=8gu39unh9l; path=/; HttpOnly, PHPSESSID=buhbhftmvotk7sk31je9e6a6r6; expires=Tue, 27-Sep-2016 20:19:47 GMT; Max-Age=1209600; path=/; secure; HttpOnly

As the cookies.  It isn't penalizing the session cookie, but saying that there are cookies being set (in this case, nette-browser) that aren't being set with the Secure flag.  Am I looking at this wrong?

Thanks!
