### ISSUE TITLE
problem starting tls scanner

### ISSUE THREAD

**Issue by moustafak** [mozilla/http-observatory#118]
According to the directions to start the scanner we should run the following command:
`HTTPOBS_DATABASE_USER="httpobsscanner" HTTPOBS_DATABASE_PASS="password" /opt/http-observatory/httpobs/scripts/httpobs-scan-worker`

Upon inspecting the postgres log:
`sudo tail /var/log/postgresql/postgresql-9.5-main.log`

`2016-09-04 05:46:45 PDT [19623-1] httpobsscanner@http_observatory LOG:  could not receive data from client: Connection reset by peer`

The API starts without issue but just the tls scanner i am having trouble with.

Any ideas how this might be troubleshooted?

**Comment by moustafak** [comment]
I am also attaching a screenshot showing the scan api not found in the console:
`POST http://localhost:57001/api/v1/scan	404 NOT FOUND	11ms`

![scan_api_not_found](https://cloud.githubusercontent.com/assets/11891112/18235345/4a6940bc-735d-11e6-8055-ce7d8e9ba3f2.png)

**Comment by marumari** [comment]
Hmm, that's very strange.  I'm out of town for the next week, but I'll take a look at this as soon as I can.

**Comment by moustafak** [comment]
Thank you! when you're back will you be able to confirm if I am using the right URL to access the TLS scanner api? I am using http://localhost:57001/api/v1/scan but not sure if that's right as it was just an assumption on my part.

Also, i wasn't sure if any settings in httpobs.conf need to be updated, i left it as default and only changed the following lines:

#url = https://http-observatory.security.mozilla.org/api/v1
url = http://localhost:57001/api/v1

#cors_origin = https://http-observatory.security.mozilla.org
cors_origin = http://localhost:57001

**Comment by marumari** [comment]
I think I know how to fix that CORS bug, but I'm currently out of town until next week and I can

**Comment by marumari** [comment]
Oh wait no, I took a look and it should allow any origin.  Can you show me the request the headers for the HTTP request that got blocked?

**Comment by moustafak** [comment]
Hi April - thanks for taking a look so soon (i know you our out until nw). I thought i'd include some additional info just in case.

Here is the Header details

![scan_api_headers](https://cloud.githubusercontent.com/assets/11891112/18296179/d332f8c8-74ea-11e6-954c-e2ff0e37a89c.png)

If I try accessing the URL directly http://localhost:57001/api/v1/scan it says Not Found

![scan_api_url](https://cloud.githubusercontent.com/assets/11891112/18296237/90ec82c6-74eb-11e6-8f88-b7a18ed69a24.png)

**scanner.log**
[2016-09-07 04:26:47,006: WARNING/MainProcess] scanner@localhost.localdomain ready.

**postgressql log**
< 2016-09-07 04:26:45.013 AEST >LOG:  connection received: host=::1 port=41645
< 2016-09-07 04:26:45.014 AEST >LOG:  connection authorized: user=httpobsscanner database=http_observatory

**redis.log**
[55093] 07 Sep 11:00:24.726 * RDB: 0 MB of memory used by copy-on-write
[36289] 07 Sep 11:00:24.793 * Background saving terminated with success

**Comment by marumari** [comment]
I'm not sure exactly where it's getting /api/v1/scan from, since it's not an API endpoint.  All of the scans are initialized via /api/v1/analyze.  Hmm.

**Comment by moustafak** [comment]
See the variable _SCAN_URL_ according to _httpobs-third-party-1.0.5.js_

Originally it was like this:

var SCAN_URL = 'https://tls-observatory.services.mozilla.com/api/v1/scan';
var RESULTS_URL = 'https://tls-observatory.services.mozilla.com/api/v1/results';
var CERTIFICATE_URL = 'https://tls-observatory.services.mozilla.com/api/v1/certificate';`

I changed to this:

var SCAN_URL = 'http://172.30.18.170:57001/api/v1/scan';
var RESULTS_URL = 'http://172.30.18.170:57001/api/v1/results';
var CERTIFICATE_URL = 'http://172.30.18.170/api/v1/certificate';

**Comment by moustafak** [comment]
Hi April,

Have you had a chance to take a look at this one?

thanks,
Moustafa

**Comment by marumari** [comment]
Sorry!  I was away at a conference!  So, I know what your issue is.  :)

The TLS Scanner isn't built into HTTP Observatory -- it's actually a different project, over here:
https://github.com/mozilla/tls-observatory

You can host your own version of it (on another port on localhost), use the Mozilla hosted version, or simply remove the call to it from the website.

**Comment by marumari** [comment]
Is this a problem, or is it okay to close this one out?

**Comment by moustafak** [comment]
Thanks April!
You may close this one.

**Comment by marumari** [comment]
Thanks!
