### ISSUE TITLE
CloudFlare's mandatory `__cfduid` cookie should not penalize site

### ISSUE THREAD

**Issue by reedloden** [mozilla/http-observatory#121]
CloudFlare sets a mandatory `__cfduid` cookie that doesn't have the `Secure` flag on it. This cookie has no security impact on the site itself and is only used by CloudFlare for whitelisting specific users from security restrictions. As such, it's presence as the only cookie without the `Secure` flag should not penalize the site.

See https://support.cloudflare.com/hc/en-us/articles/200170156 for more details.

**Comment by marumari** [comment]
Yeah, I've seen this issue before:

https://github.com/mozilla/http-observatory-website/issues/28

I'm somewhat loathe to add code exceptions simply because CloudFlare is behaving badly, but given how common it is, I may have to make an exception.  I was really trying to avoid going down this rabbit hole, because once you start adding exceptions for one provider...

**Comment by reedloden** [comment]
I agree on the rabbit hole, but sadly, CloudFlare doesn't offer any way to disable this cookie.

As for exceptions, I would just say that every exception should be handled on a case-by-case basis and must have good documentation/reasoning behind it.

**Comment by marumari** [comment]
I'll implement the exception, but I'm also giving CloudFlare the what's what in the interim, and will probably write a scathing blog post.  ;)

**Comment by floatingatoll** [comment]
Consider displaying a [0] or [-5/+5] pairing indicating that a cookie was
excepted from the process.

**Comment by spaghetti2514** [comment]
@marumari ```I'll implement the exception```

Is this still planned? I've been waiting for it to land for a while. Anything I can do to help?

**Comment by marumari** [comment]
Hopefully soon; sorry, I'm the only developer and there was/is so much to get done.  :(

**Comment by marumari** [comment]
Also, I know that this isn't tracked on the bug, but I have been talking about this with CloudFlare and trying to find ways to improve it.  Can you share what domain is being used that has this issue?

**Comment by reedloden** [comment]
hackerone.com is one example.

**Comment by marumari** [comment]
mtgowikiprice.com is another, but it doesn't set HSTS (which fixes the problem)

**Comment by marumari** [comment]
Okay, this is fixed and deployed to the live site.  I opened up #202 to track the (hopeful) eventually removal of this code.

**Comment by rugabunda** [comment]
Blocked it permanently! The great app cookiebro allows for blacklisting and whitelisting individual cookies, its the best pieces of software for cookies that I have seen yet.
