### ISSUE TITLE
design fault!

### ISSUE THREAD

**Issue by supervisitor** [mozilla/http-observatory#123]
This test is based on the basic precondition that generally everything should be transfered over ssl.

But why should I trust external sources when I visit a site? And why is this not tested???

When I visit a site of e.g. a news-paper, I get the main page from the company server and many other components from different companys, e.g. counters, analytics, api, font and tools provider.
But why should I trust them in the same way I trust the news-paper company? And why should I trust a company I do not know that I use there service?

In the past we have seen more than one, when a shared used resource has a bug, many servers are infected and the guys who use this bug have many servers to eat from! So a reason for a shared resource of fonts, api's, tools, ets. is not existent.

e.g.: This test gives us/me negaive points because I do not activate HSTS, but it don't have a look to the sources I use for all of my content. Yes, we/I could activate HSTS, but this is not a security feature! On the other site, when you open a page of our company, you will get only components from our subnet! We do not use any external resources (we use a local mirror for many of this resources where we aktivate all changes manually after a human review), and this we do of security reasons! 

When you want to judge the security of a site you should not go the mainstream! To do this, you should trust noone and this means you should not trust shared resources first!

**Comment by marumari** [comment]
Any site could have anything malicious on it, and there's no way to test for this in any kind of a remotely easy manner.  In the future, we'll hopefully add support for the SafeBrowsing API, so that we can show that sort of information.
