### ISSUE TITLE
SRI listed as not in use

### ISSUE THREAD

**Issue by ScottHelme** [mozilla/http-observatory#125]
On my results I get a warning: "Subresource Integrity (SRI) not implemented, but all external scripts are loaded over https"

https://observatory.mozilla.org/analyze.html?host=scotthelme.co.uk 

SRI is deployed on my site with the exception of one `<link>` element that fetches content from the Google Fonts API. You can't use SRI with the Fonts API as "the Fonts API serves a stylesheet generated for the specific user agent making the request".

https://developers.google.com/fonts/docs/technical_considerations#what_is_the_google_fonts_api_serving

If this is the reason I'm being marked as not having SRI then perhaps an exception needs to be made for `<link>` elements with a `href` attribute pointing to `fonts.googleapis.com`.

**Comment by marumari** [comment]
This is the tag that is causing the problems:

`<script src="https://www.google-analytics.com/analytics.js" type="text/javascript" nonce=6q857h8AXiA5L1RRfI29GqCjAhvtVjz8></script>`

Unfortunately, Google Analytics is kind of a black box and they make it generally completely impossible to use them with SRI.

**Comment by marumari** [comment]
FYI, in the console you can bring up:

`Observatory.state.results['subresource-integrity']`

And see everything that it looked at.

**Comment by ScottHelme** [comment]
Doh! Now I feel silly, I only added that in today instead of the usual method...
