### ISSUE TITLE
Redirection test should take preloading into account

### ISSUE THREAD

**Issue by marumari** [mozilla/http-observatory#126]
www.feistyduck.com (@ivanr) is preloaded, but the redirection test still penalizes it.

**Comment by ivanr** [comment]
There's another thing: I redirect from http://www.feistyduck.com to https://feistyduck.com to https://www.feistyduck.com, using 301s. Even without preloading, HSTS is enabled everywhere.

**Comment by marumari** [comment]
That is unusual, although it makes sense to enable HSTS.

It currently just tests that the initial redirection is from http -> https on the same host (to set HSTS), but I don't think I've encountered that particular roundabout redirection, even though it makes sense.  I'll think about how to fix that one as well.  :)

**Comment by marumari** [comment]
Looks like it's all working now: https://observatory.mozilla.org/analyze.html?host=www.feistyduck.com

I've added a TODO to fix the other redirection thing at some point.  :)
