### ISSUE TITLE
data request:  publish the "grade" with the scan result data

### ISSUE THREAD

**Issue by gregglind** [mozilla/http-observatory#130]
(or don't!  some things in https://github.com/gregglind/observatory-cli/issues/2 are easier if it's in the 2nd data.)

**Comment by marumari** [comment]
Currently the result query just returns test results, so you can iterate through them if you like.  If you include the overall grade, you need to start removing things from the iteration.

Each subtest does include a score_modifier, which shows how much it affected the grade.

**Comment by gregglind** [comment]
I found a fine workaround for `--expect`, no longer needed.
