### ISSUE TITLE
IPv6-only web site yields incorrect scan summary

### ISSUE THREAD

**Issue by GaryGapinski** [mozilla/http-observatory#136]
Results in SITE DOES NOT SUPPORT HTTPS.

https://status.23887er.pw/ is an example.

**Comment by marumari** [comment]
Ahh! The site actually does work in half of it -- you can see that it gets a score for HSTS (which requires it to support HTTPS).  However, it seems that the TLS Observatory doesn't support IPv6 only sites.  I'll open up a bug there.

**Comment by marumari** [comment]
Going to close this one, and track the bug on the TLS Observatory repo.  Thanks for letting me know!
