### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by hdatma** [mozilla/http-observatory#144]
The purpose of a compliance assessment is to check whether implementation A is sound and complete with respect to the standard specification B. Although a formal correctness proof would be necessary, in practical cases such as this one, where compliance is not a matter of life or death, we can skip the proof. In you case, however, not only you skip the proof, but you take the liberty of misreading the standard and ignore the issue repeatedly. In fact, this is the third (and last) time that I am reporting this! 

Normative reference
https://www.w3.org/TR/access-control/#access-control-allow-origin-response-header

```
5.1 Access-Control-Allow-Origin Response Header

The Access-Control-Allow-Origin header indicates whether a resource can be shared based by
returning the value of the Origin request header, "*", or "null" in the response. ABNF:

Access-Control-Allow-Origin = "Access-Control-Allow-Origin" ":" origin-list-or-null | "*"
In practice the origin-list-or-null production is more constrained. Rather than allowing a 
space-separated list of origins, it is either a single origin or the string "null".
```

When no resources are shared, the specification says explicitly that the value of Access-Control-Allow-Origin is the string "null". 

The mozilla compliance test ignores the above, and returns a penalty value of -50, 
that is, you get a penalty if you implement the standard correctly! 

This patch corrects the compliance test, and returns a value of +5 instead. 

http-observatory/httpobs/scanner/analyzer/misc.py

```
+# http://www.w3.org/TR/access-control/#access-control-allow-origin-response-header
+ if 'null' in domains:
+          output['result'] = 'cross-origin-resource-sharing-is-null'
+
if '*' in domains:
            output['result'] = 'cross-origin-resource-sharing-implemented-with-universal-access'
```

http-observatory/httpobs/scanner/grader/grade.py

```
# Cross-origin resource sharing
+
+# http://www.w3.org/TR/access-control/#access-control-allow-origin-response-header
+'cross-origin-resource-sharing-is-null': {
+  'description': 'Content is not visible via cross-origin resource sharing (CORS) files or headers',
+  'modifier': +5,
+},
```

**Comment by marumari** [comment]
Where exactly in the specification does it state that "null" is no origins?  If you say Access-Control-Allow-Origin: null, then files from the local file system making XHR requests (which use Origin: null) are allowed to work just fine.

**Comment by marumari** [comment]
Here is the documentation around ACAO: null:

https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null

**Comment by hdatma** [comment]
It is good that they have clarified things, at last. 

The test is still broken, however. This is the result on a server whose headers 
do not include any "Access-Control-Allow-Origin": 

`Cross-origin Resource Sharing -50 Content is visible via cross-origin resource sharing (CORS) file or headers`

**Comment by marumari** [comment]
What server?

**Comment by hdatma** [comment]
```
HTTP/2 200 
server: nginx
date: Tue, 08 Nov 2016 16:31:35 GMT
content-type: text/html; charset=ISO-8859-1
content-length: 9092
last-modified: Sun, 12 Jun 2016 20:34:29 GMT
vary: Accept-Encoding
etag: "575dc755-2384"
expires: Tue, 03 Jan 2017 16:31:35 GMT
cache-control: max-age=4838400
cache-control: private, must-revalidate
content-security-policy: default-src 'self'; block-all-mixed-content; form-action 'self'; frame-ancestors 'self'; reflected-xss block; sandbox allow-scripts;upgrade-insecure-requests;
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000; includeSubDomains; preload
public-key-pins: max-age=31536000; includeSubDomains; pin-sha256="56M+zVRS7/1TiaUPN5qImaMGT3S0fEj309gWSjnhGGs="; pin-sha256="IBe2OsltAWSQHcKdcEJqEmOoCtZSmyNhxcFB+JM7+Vc="; pin-sha256="Fbs+o+IxVNTHBpjNQYfX/TBnxPC+OWLYxQLEtqkrAfM="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="
accept-ranges: bytes

```

**Comment by marumari** [comment]
Unfortunately, that's not very helpful.  My guess is that there is a crossorigin.xml or clientaccesspolicy.xml file that is allowing flash/silverlight full access to the domain.

**Comment by hdatma** [comment]
We use crossdomain.xml, to allow reading rss content from a flash client. 

<?xml version="1.0" ?>
<!DOCTYPE cross-domain-policy SYSTEM 
"http://www.adobe.com/xml/dtds/cross-domain-policy.dtd">


<cross-domain-policy>
  
  <site-control permitted-cross-domain-policies="master-only" />
  
  <allow-access-from domain="*" to-ports="443" />
</cross-domain-policy>

**Comment by marumari** [comment]
As designed, that policy allows any piece of flash to read any piece of content on your website, with cookies.  It's very dangerous and that's why you're being penalized.  :)

**Comment by hdatma** [comment]
We distribute PDF documents with a built-in action-script (flash) that reads and displays our RSS feeds as part of the document itself. When reading a certain PDF page, the script renders the feed as if it were part of the document. The documents are distributed world-wide, and therefore the script needs to have access from any domain. This crossdomain.xml is an old policy file that needs to be rewritten. Thank you for spotting it, the observatory proved to be useful against distraction...
