### ISSUE TITLE
select_site_header never actually works

### ISSUE THREAD

**Issue by jarondl** [mozilla/http-observatory#156]
The function [httpobs.database.select_site_headers](https://github.com/mozilla/http-observatory/blob/f40218535404103563ed1a20466faa7067ecbce6/httpobs/database/database.py#L258) calls the database, and asks for `public_headers, private_headers, cookies FROM sites`. But I have not found where these get filled. I believe that they always remain `NULL`, and that this does nothing. The function always returns `{'headers: None, cookies: None}`, except when the DB is empty, in which case it returns `{}`, breaking the API, or when there is no DB and it crashes.

You may ask why I care, and the reason is that I'm trying to run the scanner without a DB, and the retriever calls this function and errors out. That is the one thing stopping me from running a DB-less scan.

PS. The code could have been simpler with `headers = row.get('public_headers', {})` in three occurrences here.

**Comment by marumari** [comment]
`row.get('public_headers', {})` will return `None` and not `{}`, which is what I need, because the value is actually NULL (None).

We actually use these columns inside Mozilla quite a bit (for testing sites that need sessions and the like), but they are currently not exposed because I haven't had the time to think of a safe way to do it.

**Comment by jarondl** [comment]
You are right about the `row.get` of-course, I haven't considered the actual `None` value.

If these columns are in use internally, then the title of this bug is wrong, but I still think that they way this code handles an empty DB result is wrong. I guess it should raise an error. Because currently it returns `{}`, while the retriever (expects)[https://github.com/mozilla/http-observatory/blob/f40218535404103563ed1a20466faa7067ecbce6/httpobs/scanner/retriever/retriever.py#L121] `headers` and `cookies` to exist.

In the DB-less scenario this code should never have been called (#157), so that's not an issue.

**Comment by marumari** [comment]
This code will be fixed in the code push that allows scans without any backend.  :)

**Comment by marumari** [comment]
Oh hey, this was fixed a while back by moving it into scan() instead of being in retrieve_all().
