### ISSUE TITLE
No warning when HSTS includeSubDomains is miscapitalized

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/http-observatory#159]
Per hstspreload.appspot.com, on a domain with the incorrect capitalization:

```
Status: people-mozilla.org is not preloaded.
Eligibility: people-mozilla.org is eligible for preloading, although we recommend fixing the following warnings:

⚠️ Warning: Non-standard capitalization of includeSubDomains
Header contains the token `includeSubdomains`. The recommended capitalization is `includeSubDomains`.
```

The observatory score report for the domain gives no indication that the header is capitalized incorrectly, especially in conjuction with ```; preload```.

**Comment by marumari** [comment]
I currently suppress warnings in the hstspreload section of the website, but I perhaps could be persuaded to change that.  This doesn't actually cause it to fail the test, so I am a bit loathe to change the description on top.

**Comment by floatingatoll** [comment]
I would be fine ignoring it if the preload site hadn't said something, but
if they care, why do they care, and is their reasoning relevant to us here?

**Comment by marumari** [comment]
You'd have to ask @lgarron why he cares, but I suspect it's not a big deal since it's just a warning and not an error.

**Comment by lgarron** [comment]
Just a warning. The advice on the internet (including hstspreload.appspot.com for some time) had lots of non-canonical capitalizations. Now that I've swayed it the other way, I'm thinking of removing the warning.

**Comment by floatingatoll** [comment]
Fine with me to close this, then! Thanks for the tip.

**Comment by marumari** [comment]
Does it make me mildly crazy that HSTS uses `includeSubDomains` and CSP uses `upgrade-insecure-requests`?  Maybe!

Hmm, `include-sub-domains` and `upgradeInsecureRequests`?
