### ISSUE TITLE
Make Chromium preload list local

### ISSUE THREAD

**Issue by marumari** [mozilla/http-observatory#160]
This way you don't need to have a network connection for stuff.

**Comment by wanshuo168** [comment]
Hello marunari, is this issue being fixing? When do you plan to update it? 
I also meet the same problem when the httpobs tool is used without internet connection.
@marumari , Thank you!

**Comment by marumari** [comment]
It is being worked on, it will just take time.  I'm basically the only developer, so I take care of things whenever I have a chance.  :)

**Comment by marumari** [comment]
Fixed in #177, woo!

**Comment by wanshuo168** [comment]
Great! Thanks for your efforts!

**Comment by marumari** [comment]
You're very welcome.  I hope that between this and the local (ie, no-db, no-redis, etc.) scans, this should have everything you need.  :)

Let me know if I can help otherwise!
