### ISSUE TITLE
Subresource integrity - unclear result

### ISSUE THREAD

**Issue by aosdf6dd** [mozilla/http-observatory#181]
Hi,

![untitled picture](https://cloud.githubusercontent.com/assets/20280659/21231953/4dd32128-c2ea-11e6-9eef-1d719155f067.png)

Looking at the scan result shown in the screenshot, the "subresource-integrity" check failed. The expectation is SRI to be implemented and all external scripts loaded securely. The result in the case above is that SRI is not implemented but all scripts are loaded securely. So I'd expect the result to be pass=TRUE, instead of pass=FALSE. The score description does not add information to make the situation more clear.

Is this a bug? Or why is the test FAILED but still telling me that everything is fine because resources are loaded via HTTPS....

Thank you!

**Comment by marumari** [comment]
It's false because what it thinks is an external resource doesn't have an integrity attribute.  I'll work on fixing the bug so that it checks for an identical absolute domain.  :)

**Comment by marumari** [comment]
Closing this because I think it's the same bug as #182.  :)

**Comment by pkrishnamraju1** [comment]
i didnt get,can u tell me in brifely

**Comment by floatingatoll** [comment]
It's a bug in the scanner, not your site. The bug is tracked in issue #182 and will eventually be fixed.
