### ISSUE TITLE
Session cookie set without the Secure flag, but transmission over HTTP prevented by HSTS

### ISSUE THREAD

**Issue by txsutton** [mozilla/http-observatory#183]
I am unsure why I am getting marked down -10 points for this

SOMETHING_SECURE=rd6o00000000000000000000ffffb938a245o80;HttpOnly;Secure;Path=/;Version=2;

The secure and HttpOnly were done via a F5 BIG-IP iRule .. is there a specific order that is required or is the syntax wrong? .. Seems to show up okay in Firebug as Secure and HttpOnly

**Comment by floatingatoll** [comment]
That cookie header violates RFC 6265 section 4.1.1 Syntax, which requires a
space to follow the semicolon field separators and does not permit the
trailing semicolon.

If you repair it to comply with the RFC as follows, does it pass
Observatory tests?

SOMETHING_SECURE=rd6o00000000000000000000ffffb938a245o80; HttpOnly;
Secure; Path=/; Version=2

**Comment by txsutton** [comment]
Perfect thanks
