### ISSUE TITLE
Invalid hostname error capitalizes the hostname

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/http-observatory#184]
This is the most trivial of all possible bug reports, but at https://observatory.mozilla.org/ I entered ```www.test.com:80``` and got back:

```Error: Www.test.com:80 is an invalid hostname```

It shouldn't capitalize the hostname there.

**Comment by marumari** [comment]
Fixed in https://github.com/mozilla/http-observatory-website/commit/81ccb15a03a097e9ee6ce9235ce6da8cd5e1cc8c.
