### ISSUE TITLE
Robustness of parsing headers

### ISSUE THREAD

**Issue by aosdf6dd** [mozilla/http-observatory#187]
You know, HTTP is quite a dirty protocol due to its numerous implementations, none of them being 100% correct with the RFC. Recently I had a server (not gonna say it was me who caused the issue when I tried to append custom headers), that returned HTTP headers as shown:

![1482251606](https://cloud.githubusercontent.com/assets/20280659/21359062/2e7172cc-c6db-11e6-8c96-bebe6c3ab249.png)

You can see, the X-XSS-Protection header has a whitespace before the separating colon, which subsequently totally confused observatory (or aborted further parsing). In the scan result the headers show up as in this screenshot:

![1482251816](https://cloud.githubusercontent.com/assets/20280659/21359296/18af2762-c6dc-11e6-90cf-d8f6c7482087.png)

Hence, the scan result was completely wrong as several headers (that were actually correct) did not get evaluated.

Maybe the solution to this problem would be to:
1. pares response headers line by line
2. split at the _first_ colon  
3. call strip on the first index (as there never are whitespaces in official and security relevant header names)
4. continue evaluation

best regards!

**Comment by marumari** [comment]
I can't see your second screenshot, but I will say that my code doesn't extract the HTTP headers: it uses the requests library for that.  I'm afraid that's not something that I can or am able to change, but you may want to submit an issue on their repository:

https://github.com/kennethreitz/requests

That said, there's a good chance that they won't fix this.  There is "dirty" and there is wrong, and I suspect this may be the latter.
