### ISSUE TITLE
Warn when an offsite HTTP redirect is followed

### ISSUE THREAD

**Issue by aosdf6dd** [mozilla/http-observatory#189]
Sorry for submitting so many issues, I hope they are appreciated and not too useless :+1: 

I have noted that observatory is blindly following 302 HTTP redirects and scanning the application/domain/URL it gets redirected to. 

As an example (imaginary domains) I tried so scan **somedomain.de** which redirected me (HTTP 302) to **https://www.nsa.gov/** and the results were finally collected for **https://www.nsa.gov/**. First of all I did not want to have results for **https://www.nsa.gov/**, and second there was no way to notice the redirect outside of the expected context. I was wondering quite a long time why the implementation of some headers on my web server was not effective according to the scan output.

I'd suggest not to follow redirects outside the given domain. The requests library does automatically follow but you can ask it to give you the actual URL you were ending up at. If the script detect to be redirected outside of the initial domain, it could (for example):
- Not return results at all, saying at the given URL there was nothing to check but only a redirect to a different application. If a user was really interested in the redirect URL, he/she could directly use it as the starting point for a scan. 
I'd prefer this solution, because if I enter a domain, I would expect results for exactly that URL and I might not notices that the domain changed, even if it was written somewhere in the results. Redirects to other ports are common (e.g. http to https) but redirects to different IPs/domains usually indicate different applications.
- At least put some fat warning in the response JSON that the final domain does not match the input domain. There is the "scan" section in the JSON result file, it could contain a flag like "targetOutsideScope". 

Generally it would be a good thing if the "scan" section in the JSON output would not only contain the HTTP response headers but also the final URL they belong to (you can query it from the requests framework after it did all the redirects). Because internal redirects are quite common and it would be usefull to see which resource actually got scanned (as different resources may have different scan results).

**Comment by floatingatoll** [comment]
#137 shares the same reasoning as this one.

**Comment by marumari** [comment]
I think it's a fine idea to add some kind of notice about it not being on the same domain, and alerting to what that is, as well as having an option to disable redirects.  I'm terribly concerned about off-domain redirects in general though, simply because you could otherwise just scan that domain anyways.

**Comment by floatingatoll** [comment]
#137 is on file for disabling redirects; updating this bug to reflect the "warn when it occurs" enhancement request. (We would totally benefit from this, too.)

**Comment by marumari** [comment]
Okay, the website should now display something like this:

**Host**:  google.com → www.google.com

Which is right up at the top.  Note that this doesn't involve any changes to the scanner; it simply looks at the last entry in results.redirection.output.route and sees if the host is different from the target.
