### ISSUE TITLE
Scoring for Opportunistic Encryption

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/http-observatory#200]
https://blog.cloudflare.com/opportunistic-encryption-bringing-http-2-to-the-unencrypted-web/

We support opportunistic encryption in the browser, so perhaps it'd be good to score the presence of Alt-Svc headers somehow (at the very least, for reporting purposes).

**Comment by marumari** [comment]
I think we actually took out opportunistic encryption, and I honestly don't want people to know or believe that it exists, so I'm going to close this out and pretend continue to ignore it with the Observatory.
