### ISSUE TITLE
Issue with Content Security Policy (CSP) implemented unsafely

### ISSUE THREAD

**Issue by opalepatrick** [mozilla/http-observatory#207]
I am getting this message in the observatory:
Content Security Policy (CSP) implemented unsafely. This includes 'unsafe-inline' or data: inside script-src, overly broad sources such as https: inside object-src or script-src, or not restricting the sources for object-src or script-src.

for this header:
Content-Security-Policy: "default-src 'none'; object-src 'self'; frame-src 'self'; img-src 'self' https://www.google-analytics.com/ 'none'; script-src 'self' https://ajax.googleapis.com/ajax/libs/ https://www.google-analytics.com; style-src 'self' https://fonts.googleapis.com/css; font-src 'self' https://fonts.gstatic.com;"

As far as I can see in multiple sources including observatory docs, I have implemented it correctly. The reference to https being an overly broad source yet is exactly what the examples suggest. The only thing I can think of is a syntax error. Can anyone see this?

**Comment by marumari** [comment]
Interesting, that looks fine.  Can you share the site name so I can do some testing?  Thanks!

**Comment by marumari** [comment]
Actually, does your header *actually* have the quotes in it?  If that's the case, it's an invalid header and that's why it's triggering this error. As a side note, you don't want both 'none' and 'self' in the same directive (as you have with img-src.  

It should look like this:

```
Content-Security-Policy: default-src 'none'; object-src 'self'; frame-src 'self'; img-src 'self' https://www.google-analytics.com/; script-src 'self' https://ajax.googleapis.com/ajax/libs/ https://www.google-analytics.com; style-src 'self' https://fonts.googleapis.com/css; font-src 'self' https://fonts.gstatic.com
```

**Comment by opalepatrick** [comment]
Hi marumari. Thanks for replying. Sorry I should have been more accurate. In this instance I have had to use .htaccess, so the actual line is:
Header set Content-Security-Policy: "default-src 'none'; object-src 'self'; frame-src 'self'; img-src 'self' https://www.google-analytics.com/; script-src 'self' https://ajax.googleapis.com/ajax/libs/ https://www.google-analytics.com; style-src 'self' https://fonts.googleapis.com/css; font-src 'self' https://fonts.gstatic.com"

**Comment by opalepatrick** [comment]
The site is www.patpatworks.com

**Comment by floatingatoll** [comment]
When I checked that site with curl, I only see a brief CSP header over
HTTPS:

$ curl -I https://www.patpatworks.com
Content-Security-Policy: frame-ancestors 'self'

And none at all over HTTP (though, it unexpectedly redirects somewhere
else):

$ curl -I http://patpatworks.com
HTTP/1.1 301 Moved Permanently
Date: Thu, 19 Jan 2017 19:07:59 GMT
Server: Apache
Location: http://www.patpatworks.com/

$ curl -I http://www.patpatworks.com
HTTP/1.1 302 Found
Date: Thu, 19 Jan 2017 19:07:18 GMT
Server: Apache
Location: https://patpatworks.com

$ curl -I https://patpatworks.com
HTTP/1.1 301 Moved Permanently
Date: Thu, 19 Jan 2017 19:08:19 GMT
Server: Apache
Location: https://www.patpatworks.com/

You may benefit from chaining the redirects as follows:

http://pat -> https://pat -> https://www.pat

http://www.pat -> https://www.pat

But none of these return the full CSP header shown, so the scanner wouldn't
see it to evaluate and score.

**Comment by marumari** [comment]
(also there should be no colon after the header name with Apache Header set)

**Comment by opalepatrick** [comment]
Thanks both. The colon was on other headers as well that were being evaluated correctly. However, I do think that the redirects are messing things up. Set by Plesk, so will have to go and sort them out properly.

**Comment by marumari** [comment]
No problem, and good luck!

**Comment by opalepatrick** [comment]
Actually it was my fault following the guide and over-writing the CSP above with Content-Security-Policy: frame-ancestors 'self' a few lines down. Should have shown all the lines in the .htaccess changes and I am sure I would not have wasted your time :-)

**Comment by floatingatoll** [comment]
No worries :)
