### ISSUE TITLE
Referrer Policy header is not parsed correctly

### ISSUE THREAD

**Issue by LeSuisse** [mozilla/http-observatory#213]
It looks like the referrer policy header is not parsed accordingly the [specification](https://www.w3.org/TR/referrer-policy/#parse-referrer-policy-from-header). Only the first policy is taken into account, the others are ignored.

For example, this header `Referrer-Policy: unsafe-url, no-referrer` gets a penalty while this one `Referrer-Policy: no-referrer, unsafe-url` gets a bonus. It is no coherent with what browsers will do, in the first case the `no-referrer` policy will be used but it gets penalized and in the second browsers will use the `unsafe-url` policy but it gets a bonus.

My example is a bit extreme, an example more likely to happen would be something like `Referrer-Policy: no-referrer-when-downgrade, same-origin`. `no-referrer-when-downgrade` can be omitted since it's the default but setting it explicitly prevent browsers that do not yet have a full support of the referrer policy header to throw a warning.

I would like to fix this issue but before opening a PR I would like to ensure the following approach is fine:
- A penalty is inflicted if one of the policy is `origin`, `origin-when-cross-origin` or `unsafe-url`
- A bonus is granted if the used policy is one of `no-referrer`, `same-origin`, `strict-origin`, `strict-origin-when-cross-origin`.

Once this is fixed it could probably be interesting to warn the user if the policies are not ordered from the most permissive to the less permissive one.

**Comment by marumari** [comment]
Are you sure that is actually the case?

https://github.com/mozilla/http-observatory/blob/master/httpobs/scanner/analyzer/headers.py#L355

It specifically uses the final value, as per the specification.

**Comment by marumari** [comment]
Ah ha, I see the issue now.  I'll have a fix and test for it up shortly.

**Comment by marumari** [comment]
Should be good now.  I'll make a deployment a bit later today.  :)

**Comment by LeSuisse** [comment]
Wow, that was a quick fix, didn't even got the time to contribute ;) . Thanks for your work.
