### ISSUE TITLE
[Feature] add detection of Same-site attribute cookies 

### ISSUE THREAD

**Issue by nico3333fr** [mozilla/http-observatory#218]
Hi,

there is a new attribute "same-site" for cookies (with value SameSite=Strict or SameSite=Lax) which could be useful to mitigate some CSRF issues https://tools.ietf.org/html/draft-west-first-party-cookies-07

Chrome is already supporting it, Firefox is also working on it https://bugzilla.mozilla.org/show_bug.cgi?id=795346

Maybe in a near future, Observatory website could detect it and score accordingly ?

Cheers,
Nicolas

P.S. : see https://scotthelme.co.uk/tough-cookies/ and https://scotthelme.co.uk/csrf-is-dead/ for some examples

Tranfered for https://github.com/mozilla/http-observatory-website/issues/92

**Comment by marumari** [comment]
Duplicate of #64.  :)
