### ISSUE TITLE
Add penalty for using deprecated X-* CSP headers

### ISSUE THREAD

**Issue by edmorley** [mozilla/http-observatory#223]
From https://content-security-policy.com : 
> Note: It is known that having both Content-Security-Policy and X-Content-Security-Policy or X-Webkit-CSP causes unexpected behaviours on certain versions of browsers. Please avoid using deprecated X-* headers.

As such I think it makes sense to warn if a site is sending the deprecated `X-Content-Security-Policy` or `X-Webkit-CSP` headers in addition to `Content-Security-Policy`, and reduce the score accordingly.

**Comment by jonathanKingston** [comment]
The advice should probably mention it's fine to send conditionally the
right header to supporting browsers though.

**Comment by edmorley** [comment]
According to the browser support table on that page and/or caniuse.com, the browsers that support `X-Content-Security-Policy` but not `Content-Security-Policy`, are:
* Firefox 4 to 22 (released <= May 2013)
* IE 10 and 11 (but they only support the `sandbox` directive)
* Edge 12 build <10240 (which were early builds before the [first public release](https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history))

And similarly for `X-Webkit-CSP`:
* Chrome 14 to 24 (released <= Nov 2012)
* Safari 6 and 6.1 (released <= Jan 2013)

As such, aside from IE 10/11 (which only support the `sandbox` directive anyway) there doesn't appear to be much benefit in special-casing the others.

**Comment by marumari** [comment]
Is there any documentation about exactly what these unexpected behaviors are?  The website doesn't link to any specific sources.

**Comment by floatingatoll** [comment]
I think we'd be better to collect this information as a simple test
("Backwards-compatibility CSP headers observed") and see what the
observatory sees over time before charging -5 for it, unless a severe
breaking behavior can occur.
