### ISSUE TITLE
Add support for `Expect-CT` header

### ISSUE THREAD

**Issue by craigfrancis** [mozilla/http-observatory#224]
Might be a little early yet, but the `Expect-CT` header is likely to be implemented in Chrome and Firefox:

https://www.chromestatus.com/feature/5677171733430272

**Comment by april** [comment]
Awesome, I hope to add support for a bunch of new features coming up in the next quarter.  :)

**Comment by floatingatoll** [comment]
Craig, what Expect-CT header would you eventually be recommended for
general use, based on the current draft?

**Comment by craigfrancis** [comment]
Really depends on the website.

Probably something like the following for a strong version:

    Expect-CT: enforce; max-age=31536000; report-uri="https://example.com/expect-ct-report"

But I'd recommend many websites to not include `enforce` at first, and see how many reports they receive; in the same way that you should implement `Public-Key-Pins-Report-Only`

---

That's not to say that `enforce` will be as bad as getting `Public-Key-Pins` wrong - as it's just saying your cert is in the Certificate Transparency log, where all Certificate Authorities will be required to do their part by [October 2017](https://groups.google.com/a/chromium.org/forum/#!topic/ct-policy/78N3SMcqUGw).

But the actual process of getting that log entry to the browser via `OCSP Stapling`, `TLS extension`, or `X.509v3 extension` ([more info](https://www.certificate-transparency.org/how-ct-works)) might take a little longer; especially as [Apache 2.4.20](https://github.com/trawick/ct-httpd/tree/master/src/2.4.x) has only just implemented [mod_ssl_ct](https://httpd.apache.org/docs/trunk/mod/mod_ssl_ct.html), and certain Certificate Authorities ([like LetsEncrypt](https://community.letsencrypt.org/t/will-you-support-certificate-transparency/222)),  won't be implementing the `X.509v3` version.

It should also be noted that this header hasn't been implemented in any browser yet (Chrome are working on it), so there might be some changes to the specification.

For example, I think it should include an `includeSubDomains` directive: https://github.com/httpwg/http-extensions/issues/322

**Comment by craigfrancis** [comment]
And thanks @april, if there is a chance of a sneak peak of the next version, please let me know... I'd be happy to do some beta testing :-)

**Comment by floatingatoll** [comment]
Okay, thanks!

**Comment by april** [comment]
There aren't so much sneak peaks as, well, I pick a task and then spend a week coding it and it's done.  :)

**Comment by craigfrancis** [comment]
Sounds like a nice way to work... says he with about 3 or more jobs on at the same time :-)

**Comment by jacobbednarz** [comment]
Please let me know if you'd like a production domain for testing or someone to guinea pig this for you. We've got this deployed for all users and will have a pretty decent telemetry within a week or so.

**Comment by april** [comment]
Absolutely, that would be great! I'm just finishing up one huge reworking, in adding support for HTTP Equiv values.  :)

**Comment by jacobbednarz** [comment]
Ah yes, that _other_ thing I was pestering you about :P

Please sing out with whatever you need and I'll send it over.

**Comment by yvele** [comment]
As I understand `Expect-CT` was only created to prepare for Certificate Transparency generalisation. As this happened more than a year ago, in April 2018, do we still need `Expect-CT`? Is my interpretation correct?

**Comment by jacobbednarz** [comment]
@yvele the HTTP `Expect-CT` header was useful during the certificate transparency rollout but it's also a measure you want to keep in place to confirm CT continuity and that CA's are doing the right thing.

**Comment by LeoMcA** [comment]
Expect-CT has been deprecated: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT
