### ISSUE TITLE
HTST Header Present is misleading when a root domain does not provide an HTST header

### ISSUE THREAD

**Issue by theghall** [mozilla/http-observatory#225]
I set up HTST with CloudFlare, but what they did not tell me is that I would not get HTST with my root domian (mydomain.com) only my sub-domain (www.mydomain.com)  since I only had a partial account (read free).  So, while the redirect is correctly noted and that redirect gives an HTST header, the browser does not detect the HTST header when starting from http://mydomain,org and thus only does a 301 redirect not a 307 redirect. (I verified this in Chrome Dev tools).   When starting from http://www.mydomain.com the browser does a 307 redirect.

When I attempted to check my preload elgibility on mydomain.com, I was denied because it said no HTST header was present, which led me to contact CloudFlare.

**Comment by theghall** [comment]
I am wondering if to fix this problem: I have to turn off HTST, wait 6 months, and then turn HTST on the actual host where my sub-domain could give an HTST header.  Or if I set up the  HTST header on my actual host first, and then turn off HTST on CloudFlare.

**Comment by floatingatoll** [comment]
This is a common issue people encounter with HSTS, and fixing it requires
taking a different approach to redirects. Set your redirects as follows:

# Redirect #1 of 2: non-www

# https upgrade ONLY, do not change sites yet
http://mydomain.com -> https://mydomain.com

# safe to redirect to offsite, verify Location + Strict-Transport-Security
in response
https://mydomain.com -> final-url-here

# Redirect #2 of 2: www

# https upgrade ONLY, do not change sites yet
http://www.mydomain.com -> https://www.mydomain.com

# safe to redirect offiste, verify Location + Strict-Transport-Security in
response
https://www.mydomain.com -> final-url-here

And repeat the above recipe for mydomain.org and www.mydomain.org.
Presumably on of your four https:// URIs is the final-url-here value, so
for that URI, you still must have an HTTP->HTTPS same-domain redirect in
place (as above), but you can (obviously) skip the offsite redirect section.

 - R.

ps. HSTS typically has little or no influence on 301/307, make sure your
web server explicitly declares 301/302 or 307/308 on each of the redirects
above. Apache permits a numeric option to Redirect 30x and to RewriteRule
[R=30x,L].

**Comment by floatingatoll** [comment]
You may also simply choose not to do these series of steps. For any URI
where you redirect http://one to https://two, you will fail to apply HSTS
to 'one', as no attempt is ever made to load from https://one (and thus
trigger an STS header).

Long-term, if you intend to permanently offer all browser services from
your domain as HTTPS, then you can submit your entire domain to the HSTS
preload list, which will cause all browsers to require https:// for all
URLs at your domain starting around 6 months from when you submit it. This
is a permanent listing and cannot be removed once added.

**Comment by floatingatoll** [comment]
The preload list requires you to advertise HSTS for the root domain, without exception, and so if you cannot persuade Cloudflare to offer HSTS for the root domain, you will have to make alternate arrangements somehow.

**Comment by floatingatoll** [comment]
Closing as there's nothing the Observatory can do to make this situation easier for you. Hopefully something in the above is of some use to your efforts. Thank you for trying!
