### ISSUE TITLE
Outdated (or overly general) list of Mozilla domains?

### ISSUE THREAD

**Issue by bfin** [mozilla/http-observatory#227]
Hi. I understand Observatory is primarily an internal tool, so I appreciate you accommodating non-Mozilla folks who use it to stay on top of things.

I was scanning one of our sites through your service and noticed that it was penalized for not including a `contribute.json` file, which I learned you use to track bugs on Mozilla domains. This appears to be the result of comparing the domain name without including the top level domain (https://github.com/mozilla/http-observatory/blob/master/httpobs/scanner/analyzer/content.py#L48-L49) against an internal list of Mozilla-operated domains. The site in question&#8202;—&#8202;[https://acat.io](https://acat.io)&#8202;—&#8202;is not a Mozilla site, but it's being treated as one because you probably have an acat.org or similar somewhere in the wild.

Could you please update your `SCANNER_MOZILLA_DOMAINS` environment variable&#8202;—&#8202;or better&#8202;—&#8202;check against complete domain names before assessing penalties?

If this is too much trouble, would you be amenable to a pull request with a whitelist for sites that share a domain name (sans top level domain) with a Mozilla site somewhere?

Thanks.

Other relevant sections of code:
Lines where the domain is checked against the list of Mozilla domains:
https://github.com/mozilla/http-observatory/blob/master/httpobs/scanner/analyzer/content.py#L76-L77

Line where the list of Mozilla domains is pulled from an environment variable:
https://github.com/mozilla/http-observatory/blob/master/httpobs/conf/__init__.py#L89

**Comment by floatingatoll** [comment]
April - for whatever it's worth, I haven't come across "ACAT.IO" in my time
here. Not sure what the live config is. Looks like the word "vacation"
minus a couple letters, in case that uncovers anything.

**Comment by april** [comment]
What actually is happening here is not that acat.io is on a list of mozilla websites, but that it replies back with a contribute.json file and a 200 status code:

https://acat.io/contribute.json

The Observatory *does* grade you if it sees a contribute.json, it just doesn't penalize non-Mozilla domains if it's not there.  In this case, acat.io is responding back with a 200 status code, application-type of application/json, and then an HTML document.  All of which are probably wrong here and is why the Observatory is confused here.

**Comment by bfin** [comment]
Thanks for clearing that up @april !

**Comment by april** [comment]
You're very welcome!  Glad I could clear it up for you!
