### ISSUE TITLE
Observatory doesn't take into account (bonus) points anymore

### ISSUE THREAD

**Issue by Razerwire** [mozilla/http-observatory#252]
This morning I've tested https://www.bonnieradvocaten.nl with the Observatory.

To my dismay our score dropped from 85/100 (A-) to 75/100 (B).

It seems that, when calculating the total score, the observatory doesn't take into account the use the Referrer-Policy "no-referrer" which should raise the total score with +5 points, furthermore the use of XFO via CSP (which should account for +5 points) is ignored when calculating the total score.

**Comment by Nightfirecat** [comment]
That is expected behavior now; you must earn at least 90 points before extra credit will be added: https://github.com/mozilla/http-observatory/pull/249/files#diff-3322d6b3f471382a95cd3a089fcf4510R38

**Comment by Razerwire** [comment]
@Nightfirecat 
Then the [Scoring Methodology page](https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/scoring.md) should be edited to reflect the changes to the scoring metholodgy.

**Comment by floatingatoll** [comment]
Reopened your issue mozilla/http-observatory-website#122 and we'll continue repairs there, thanks!
