### ISSUE TITLE
Remove 'image' entry for database in docker-compose.yml

### ISSUE THREAD

**Issue by cduranleau** [mozilla/http-observatory#253]
The current name for the DB is inconsistent with the other entries in the docker-compose.yml. Below is the output of running 'docker-compose build' where 'postgres' is repeated once for the original Postgres image and once for the built image. The compose.yml will need to be updated to depend on the new image name. 

```
M1711995:http-observatory cd033922$ docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED              SIZE
httpobservatory_postgres                                 latest              25b898d94292        About a minute ago   269MB
httpobservatory_scanner                                  latest              c3ff86a36260        2 minutes ago        725MB
httpobservatory_website                                  latest              c3ff86a36260        2 minutes ago        725MB
postgres                                                 latest              aef139b0ffc6        3 minutes ago        269MB
redis                                                    latest              a1b99da73d05        3 days ago           106MB
python                                                   3.5                 0a5c3ea81b62        9 days ago           684MB
postgres                                                 <none>              f8d91fbcfa35        2 weeks ago          269MB
```

1. https://github.com/mozilla/http-observatory/blob/05f6b5b89654878fe0c910e5f829fa902f3460b9/docker-compose.yml#L37

**Comment by cduranleau** [comment]
If I'm not mistaken, this can lead to a situation where the DB image is built from a previous version of itself. That's not a huge problem but it could introduce bugs in the future. 

Working on a sample patch now.

**Comment by april** [comment]
Ahh, cool, thanks for letting me know. I don't usually build the Observatory via Docker so a lot of the various issues with it kind of slip under the radar.  :)

**Comment by cduranleau** [comment]
No worries. A few of the people on the team have been playing with HTTPObservatory and we wanted to contribute back. Should have something submitted this afternoon.

**Comment by cduranleau** [comment]
PR: https://github.com/mozilla/http-observatory/pull/254
