### ISSUE TITLE
Possible bug when using SRI i.e no score

### ISSUE THREAD

**Issue by cjc1867** [mozilla/http-observatory#258]
Hi
As far as I know and using a WordPress plugin I only have 1 external CDN resource that has been hashed but I get no score.

Website in question is https://towywebdesigns.uk

I'd appreciate any help to fix this problem.

Thank You

Colin

**Comment by floatingatoll** [comment]
This may be contributing to that problem:

<script
                    data-cfasync="false"
                    type="text/javascript"
                    src="//
s7.addthis.com/js/300/addthis_widget.js#pubid=wp-1da109ebac00d6924ec9e022c79439dd
"

                >

This is an offsite <script src> with no integrity="" attribute.

**Comment by floatingatoll** [comment]
This may be contributing to that problem:

```
<script
                    data-cfasync="false"
                    type="text/javascript"
                    src="//
s7.addthis.com/js/300/addthis_widget.js#pubid=wp-1da109ebac00d6924ec9e022c79439dd
"

                >
...
Cached page generated by Borlabs Cache - more information https://borlabs.io/
Time to create cache: 0.55149817 sec
Time to load cache: 0.71040583
Cache file created on: 2017-07-26T12:12:21+00:00
Current time: 2017-07-26T15:55:30+00:00
```

This is an offsite <script src> with no integrity="" attribute.

**Comment by april** [comment]
Ahh yup, that's definitely it. To pass the SRI test, you must have the integrity attribute set on all external scripts, not just some of them.
