### ISSUE TITLE
Support cookies in http-equiv meta tags

### ISSUE THREAD

**Issue by april** [mozilla/http-observatory#265]
In addition to Referrer-Policy and CSP, cookies can also be set in http-equiv tags. We should check those too.

**Comment by Malvoz** [comment]
I haven't done a whole lot of research but I know that Google does not support this. And a quick check on [MDN](set-cookie) says that `<meta http-quiv="set-cookie" content="...">`:

> was removed from the standard, and is no longer supported at all in Firefox 68 and Chrome 65.

**Comment by floatingatoll** [comment]
Is it, or was it, supported by CLI clients such as Python requests or node
xyz or etc?

Is the deprecated use considered harmful enough that it deserves a negative
penalty if present?

**Comment by april** [comment]
Requests doesn't parse HTML, so I would be extremely surprised. I don't think there is much support left anymore.

As such, I think I shall probably close this bug out. Woo!
