### ISSUE TITLE
Combine multiple HTML meta tags together and with any header values

### ISSUE THREAD

**Issue by travisspencer** [mozilla/http-observatory#266]
#105 added support for specifying the CSP rules in the HTML `meta` tags. When a site has multiple of these tags, however, they are not combined correctly. The [CSP spec says](https://www.w3.org/TR/CSP2/#delivery-html-meta-element):

> 3.3. HTML meta Element
>
>The server MAY supply policy via one **or more** HTML meta elements with http-equiv attributes that are an ASCII case-insensitive match for the string "Content-Security-Policy". 

Any meta tags should also be combined with any in the HTTP response headers which is what this note in that same section of the CSP spec is getting at:

> Note: A policy specified via a meta element will be enforced along with any other policies active for the protected resource, regardless of where they’re specified.

**Comment by april** [comment]
It already does the latter of the two.  :)

**Comment by travisspencer** [comment]
Nice, @april ! Has this fix been deployed to observatory.mozilla.org?

**Comment by april** [comment]
It has, but that doesn't fix your particular website with its non-200 error code.  :)

**Comment by travisspencer** [comment]
I got - 20 for bad CSP (which I thought this ticket was meant to fix) and -
5 for being a non 200? I really don't follow the logic there.

**Comment by april** [comment]
You were affected by both bugs. It doesn't look at page text at all when there isn't a 200, so it doesn't see your CSP headers (combined or not).
