### ISSUE TITLE
Error pages must be secure as well

### ISSUE THREAD

**Issue by travisspencer** [mozilla/http-observatory#267]
> the Observatory has historically only looked at the page's contents when it returns a 200 code, not 400 or 404.

-- @april in #105 

This behavior should be changed. The Observatory should report the security ranking of the Web site under test regardless of the HTTP status code returned. If the site returns an error, the HTTP response should not put the visitor or operator at risk. 

Therefore, status codes >= 400 should be evaluated in the same manner as those returning a 200.

**Comment by april** [comment]
Just committed some code (e8f9944e91599639cb8f9079510f8fc4f6cb37e3) to track status codes. Having the ability to notify users that the page wasn't 200 (OK) is first step towards making this thing work.

**Comment by april** [comment]
Further work done in 41e526d5accce67de35d69a079b42eb05b4fdc01.

**Comment by april** [comment]
Looks like things are working now:
https://observatory.mozilla.org/analyze.html?host=nordicapis.curity.io

**Comment by travisspencer** [comment]
Spectacular, April. Thanks for all the hard work and support.
