### ISSUE TITLE
Analyse call with axios failing

### ISSUE THREAD

**Issue by benmccallum** [mozilla/http-observatory#275]
Hi there,

I'm trying to make a POST  to /analyze. I was using the [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), but then swapped over to [axios](https://github.com/mzabriskie/axios) as I needed to be able to cancel AJAX requests. Since swapping, I'm getting an error on a CORS header not being supported by the server. I'm guessing axios is requesting support for a header that plain-old fetch doesn't and your server doesn't support it. At least I think that's what it is anyway. 

Error in browser console:
> Failed to load https://http-observatory.security.mozilla.org/api/v1/analyze?host=www.google.com: Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

Repro here: https://jsfiddle.net/benmccallum/sfcfwk0u/3/

**Comment by benmccallum** [comment]
Nevermind, looks like the POST has to be of format `application/x-www-form-urlencoded` and axios' default is `application\json`. 

Updated fiddle that works here:
https://jsfiddle.net/benmccallum/u78rqwp3/2/

I guess it's implied in the docs that the format is x-www-form-urlencoded in the final example which has the post data as an ampersand delimited string, but might save some people some time by indicating in the doc it ONLY supports that format (and not json which would be the standard these days).

**Comment by april** [comment]
That's a good idea. Actually, could you please open up a bug to allow either JSON or POST data?
