### ISSUE TITLE
CSP3 Analysis - Add base-uri check

### ISSUE THREAD

**Issue by craigfrancis** [mozilla/http-observatory#281]
Could there be an argument to check base-uri 'none', as it’s not part of default-src, and most sites should probably use 'none'.

https://www.w3.org/TR/CSP/#directive-base-uri

**Comment by floatingatoll** [comment]
If this check is accepted and implemented as a penalty, consider whether to
penalize sites that don’t use relative URIs anywhere.

**Comment by craigfrancis** [comment]
@floatingatoll ... might be something to raise as a separate issue, or discuss via another medium, but what do you mean by penalising sites that "don't use relative URIs anywhere"?

**Comment by craigfrancis** [comment]
Thanks April :-)

**Comment by april** [comment]
FYI, this is now live on the main site.  :)

**Comment by craigfrancis** [comment]
Thanks again... I'm glad to see this kind of CSP analysis appear, as I've seen at least one site implement `default-src *`, which kind of defeats the purpose :-)
