### ISSUE TITLE
Don't penalize Heroku apps using session affinity

### ISSUE THREAD

**Issue by mathjazz** [mozilla/http-observatory#282]
Heroku [session affinity](https://devcenter.heroku.com/articles/session-affinity) cookie is set without a `HttpOnly` flag, effectively reducing the Observatory score of each Heroku app using session affinity by 30 points.

We should contact Heroku to set HttpOnly on this cookie.

We could also whitelist the cookie if Observatory supports such mechanism.

**Comment by april** [comment]
FYI, I've opened up a bug with Heroku on this. I'll work on getting it whitelisted soon.  :)

**Comment by april** [comment]
Deployed, looks much better now!  :)

https://observatory.mozilla.org/analyze.html?host=pontoon.mozilla.org

**Comment by mathjazz** [comment]
Thanks! :)

**Comment by april** [comment]
You're very welcome! I always appreciate any feedback on the Observatory, and I'm glad you find it helpful.  :)

**Comment by eduardo-amaro-maciel** [comment]
Hello, I'm doing a cookie categorization, on the site where I'm doing it, a cookie with the name "heroku-session-affinity" appeared, could you tell me what it's for? Grateful...
