### ISSUE TITLE
Return ETA in Scan object so client's can poll for final state more reasonably

### ISSUE THREAD

**Issue by benmccallum** [mozilla/http-observatory#287]
I was thinking it'd be good to be able to have an ETA in the /analyze Scan object of a non-completed scan that gives an indication of when it'll be done. Either as a estimated time remaining of estimate time of completion.

Basically that would mean your clients could delay their poll for the results until that ETA, saving them computation and also your server. (Assuming everyone is just hitting your server over and over again without waiting or after waiting a short time. It could be that they do wait reasonable times and this wouldn't do much for the server at all I suppose).

Depending on how you're storing data and how complex you want to get it could be based on:
* Time it took for last scan (probably not that accurate as I'm sure you scan relies heavily on the response time of the site being tested too)
* Time it took for last x scans (a bit better but more computationally intense if that's an issue)
* Time it took for last x scans under similar load, maybe a sample from the same time last week.

On subsequent polls where the ETA was passed but the scan still isn't complete you could maybe come up with something arbitrary or again look at historical scan times going over if you can or could track that.

**Comment by floatingatoll** [comment]
Would a “wait X seconds before next poll” response meet all of your needs?

**Comment by april** [comment]
Given that the average scan time is in the range of 10 seconds or so, I'm not sure it would be worthwhile to make the extra database calls necessary to calculate this. It's not like SSL Labs or the like where it's making dozens of discrete connections and can use each one as a rough benchmark of completion percentage.

It's further complicated by the fact that for the Observatory 99% of the time is spent in network I/O and 1% in actually running the tests, which makes it really hard to calculate progress.

**Comment by benmccallum** [comment]
Awesome, no worries. I didn't realise the scan time was that low! It doesn't seem like what I've been seeing my end, but that might be a network latency issue my end and I'll investigate. Thanks for the prompt response.

**Comment by april** [comment]
Do you have a site that you've had slow scan problems with? When you're staring at a screen, 10 seconds can feel a really long time.  :)

**Comment by benmccallum** [comment]
Yea you're probably right, I just thought I was seeing some logging I was doing indicating it was polling again but I'll take a look. Thanks again guys!
