### ISSUE TITLE
Base-URI possible bug?

### ISSUE THREAD

**Issue by nico3333fr** [mozilla/http-observatory#292]
Hello,

while running a test on one of my websites, I was a bit surprised of a comment in Content Security Policy Analysis :
https://observatory.mozilla.org/analyze.html?host=van11y.net

The tests says that `Restricts use of the <base> tag by using base-uri 'none', base-uri 'self', or specific origins` is not ok.

Correct me if I'm wrong or missing something: my CSP directives have `default-src` set to `none`, so as the `base-uri` is not defined in the CSP header, it should be `base-uri: none` that is applied ?

Thanks for your advices,
Nico

**Comment by floatingatoll** [comment]
I don’t think default-src controls the base-uri directive at all:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src

**Comment by nico3333fr** [comment]
@floatingatoll correct, I was not aware of it, confirmed by the spec https://www.w3.org/TR/CSP2/#directive-base-uri 

Sorry for the question and thanks for the answer.

**Comment by floatingatoll** [comment]
No worries! Another pitfall is that, IIRC, default-src does not control all
*-dev directives - just most of them!
