### ISSUE TITLE
domains that return HTTP/200 instead of HTTP/404 for /contribute.json are incorrectly identified as mozilla domains

### ISSUE THREAD

**Issue by globau** [mozilla/http-observatory#293]
while it logs the mozilla irc network (amongst others), https://logbot.info/ isn't a mozilla asset and shouldn't be penalised for a missing `contribute.json`.

**Comment by globau** [comment]
since i filed this issue i tried creating the following `contribute.json`, which is valid according to http://contributejson.org/

    {
      "name":"LogBot",
      "description":"IRC logging",
      "repository":{
        "license":"MIT",
        "url":"https:\/\/github.com\/globau\/logbot"
      }
    }

however disparity between mozilla's mandatory keys (`name, description, bugs, participate (particularly irc and irc-contacts), and urls`), and contributejson's (`name, description, and repository`) results in a penalty due to "missing some of the required keys".

**Comment by floatingatoll** [comment]
https://login.mozilla.com/contribute.json has a very simple example that
still manages to have more keys than Observatory strictly requires, in case
that helps.

**Comment by globau** [comment]
thanks; i could fill out some vague info to keep observatory happy, however i'm still confused as to why logbot.info is classified as a mozilla property :)

**Comment by floatingatoll** [comment]
I imagine for the same reasons that bugzil.la gets misclassified as a
Mozilla property now and then.

**Comment by returntrip** [comment]
I have the same issue with two of my domains. An instance of Nextcloud and an instance of Gogs. Observatory complains that 'contribute.json' cannot be parsed.... Anything that I can do to avoid this issue?

**Comment by floatingatoll** [comment]
We’d need to know the two domains in question to assist further. (If you’d
rather not share publicly, let us know and we’ll offer an email address.)

**Comment by returntrip** [comment]
thanks for the quick reply. Would like to share privately. :)

**Comment by floatingatoll** [comment]
I’m atoll @mozilla com

**Comment by danielhartnell** [comment]
I have also run into this issue with the analytics.amplitude.com:
https://observatory.mozilla.org/analyze.html?host=analytics.amplitude.com

The site is not a Mozilla property and it should not have been categorized that way.

**Comment by april** [comment]
Sorry, I just noticed this. I had it structured the way I did under the assumption that if people wanted to include a `contribute.json`, then they probably would want it validated against a good set of rules. @returntrip, @globau, can you clarify more why you wouldn't want it checked?

Instead of changing the if/else logic, I can simply not penalize non-Mozilla sites, but still let them know if they have a good set of minimum keys.

**Comment by globau** [comment]
thanks april – as long as you have two definitions of "good set of minimum keys" then that sounds good.

ie. mozilla domains must have `name`, `description`, `bugs`, `participate`, and `urls` (as per https://wiki.mozilla.org/Security/Guidelines/Web_Security#contribute.json).

non-mozilla domains must have `name`, `description`, and `repository` (as per https://www.contributejson.org/schema).  i don't think warning if other fields are missing is of value.


for anyone else with a domain hitting this problem, make sure requests for `/contribute.json` return http/404, not http/200.

**Comment by floatingatoll** [comment]
To offer a different viewpoint, I would assert that the ‘bugs’ property is
the sole property I care to see defined from a security perspective, even
if it’s a mailto: URI, since that’s the Most Critical property for security
issue reporting in my book.

**Comment by globau** [comment]
i don't disagree, but that sounds like something to change on https://contribute.json/ (https://github.com/mozilla/contribute.json).  once `bugs.report` is flagged as mandatory (or least recommended) then observatory can follow suit.

**Comment by floatingatoll** [comment]
That’s an excellent point. I’m not going to take any actions right now
while April considers all this, but I’m happy to be tasked with pursuing
that at any time.
