### ISSUE TITLE
Changes to HPKP scoring given Chrome's intent to deprecate

### ISSUE THREAD

**Issue by edmorley** [mozilla/http-observatory#294]
It appears as through Chrome/Blink will soon stop supporting HPKP headers, according to this intent to deprecate:
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/he9tr7p3rZ8

If the [HPKP MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning) is correct, this will just leave Firefox & Opera supporting HPKP (since Edge, Safari, IE hadn't already added support), and it's possible they'll follow suit.

As such, it looks like the HTTP Observatory scoring will need to be adjusted - presumable first to give no score at all for HPKP, and then later to give a negative score for including a legacy header.

**Comment by daybugging** [comment]
Any news on this?

**Comment by floatingatoll** [comment]
Resolved by #295, most likely.

**Comment by april** [comment]
Sorry! Yes, it has been fixed, it just hasn't been pushed out to the scanner. I was on leave the last few weeks, so no pushes to the scanners have been done. I have a CSP bug I'm working on and once that's fixed I'll push out both fixes at the same time.

Thanks for your patience!

**Comment by april** [comment]
This is now done - you can see it deployed here:

https://observatory.mozilla.org/analyze.html?host=scotthelme.co.uk
