### ISSUE TITLE
Error running with PostgresSQL 10

### ISSUE THREAD

**Issue by johnguant** [mozilla/http-observatory#298]
When using postgres 10 the scan-worker causes the following error when trying to fetch sites to scan 
```
postgres_1  | 2017-11-28 21:16:48.519 UTC [33] ERROR:  source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression at character 54
postgres_1  | 2017-11-28 21:16:48.519 UTC [33] STATEMENT:  UPDATE scans
postgres_1  | 	                         SET (state) = ('STARTING')
postgres_1  | 	                         FROM (
postgres_1  | 	                           SELECT sites.domain, scans.site_id, scans.id AS scan_id, scans.state
postgres_1  | 	                             FROM scans
postgres_1  | 	                             INNER JOIN sites ON scans.site_id = sites.id
postgres_1  | 	                             WHERE state = 'PENDING'
postgres_1  | 	                             LIMIT 15
postgres_1  | 	                             FOR UPDATE) sub
postgres_1  | 	                         WHERE scans.id = sub.scan_id
postgres_1  | 	                         RETURNING sub.domain, sub.site_id, sub.scan_id
```

**Comment by april** [comment]
Interesting! I don't have a PostgreSQL 10 machine to test on, but in:

https://github.com/mozilla/http-observatory/blob/master/httpobs/database/database.py

Could you change every instance of:

`SET (state) = (%s)` to `SET state = %s` and see if that fixes things? I think that's the problem, but it's a backwards incompatible change with PostgreSQL 10 and it's not terribly well documented.

Thank you!

**Comment by johnguant** [comment]
That seems to fix it in PostgreSQL 10 and still works in 9.

**Comment by april** [comment]
Awesome, thank you so much for being willing to test that. I'll push out an update sometime today with it.
