### ISSUE TITLE
Scans getting stuck and not successfully completing

### ISSUE THREAD

**Issue by benmccallum** [mozilla/http-observatory#301]
I'm getting a large number of scans just hanging on 'in progress' for ages and then being aborted. Is the service having issues?

**Comment by benmccallum** [comment]
FYI if I try the same URL on your site directly, I get the same result. Hangs and then aborts/fails.

**Comment by april** [comment]
Yeah sometimes the scanner gets stuck due to a weird celery issue. I've been trying to track it down for a year without much luck. I did kick things and it seems back to normal now.

**Comment by benmccallum** [comment]
Thanks :)
