### ISSUE TITLE
Need to white list Observatory IP's to test a locked down site

### ISSUE THREAD

**Issue by Joe8west** [mozilla/http-observatory#306]
Hi,

I need to test an environment that's private so Im looking for the IP's to whitelist so that I can run Observatory against it. Ive tried to find contact details elsewhere and have been on other forums but with no success. I hoping I can find them here as this is my last ditch effort :)

**Comment by floatingatoll** [comment]
The README includes instructions for running your own command-line (or full
website!) instance of Observatory, and I use them regularly to test our
internal sites. Would that work for you here as well?

**Comment by Razerwire** [comment]
When scanning with Mozilla's Observatory i'm seeing traffic coming from:
`63.245.214.162`
That's the IP-adress of the Mozilla Server performing the scan.

Furhermore SSH-scanning is done via  `sshscan.rubidus.com` at `45.55.176.164`.

**Comment by Joe8west** [comment]
Thanks for the suggestions - I dont think it will be possible to run our own instance due to red tape but I'll try the IP suggestions - thanks for the help

**Comment by april** [comment]
You don't even necessarily need to run your own instance, as httpobs-local-scan can perform scans from just a local installation without having any databases or the like installed.
