### ISSUE TITLE
Check parent domain for HSTS preload on subdomains

### ISSUE THREAD

**Issue by MekliCZ** [mozilla/http-observatory#311]
On subdomains, Observatory checks if the subdomain is preloaded which is impossible. It should check if the parent domain is preloaded.

**Comment by april** [comment]
It already does do that.  :)

**Comment by MekliCZ** [comment]
@april <img width="890" alt="snimek obrazovky 2018-01-17 v 20 09 11" src="https://user-images.githubusercontent.com/9162439/35061707-4f7c9bdc-fbc2-11e7-8c59-b7eafb24b9df.png">

**Comment by april** [comment]
Oh, I see what you're saying it. It does check it for the parent domain in the Strict Transport Security test:

https://observatory.mozilla.org/analyze.html?host=www.pokeinthe.io

Where `pokeinthe.io` is preloaded. The third party tests are tricky - it's actually quite difficult to get a parent domain to send. What I would suggest is opening up a bug with the hstspreload folks:

https://github.com/chromium/hstspreload.org

And suggest that their API return that the parent domain is preloaded. With that, I would happily change how the third party tests are reflected.

**Comment by MekliCZ** [comment]
I think it isn't that hard to get parent domain using Public Suffix List (https://publicsuffix.org).

**Comment by april** [comment]
Yes, and that's what the HTTP Observatory already does for its check. I don't want to add an additional JavaScript library to pull out the TLD to send to a third party, when it that check should probably be on their side to begin with.
