### ISSUE TITLE
Honor CSP referrer option

### ISSUE THREAD

**Issue by exploide** [mozilla/http-observatory#312]
Instead of sending the separate `Referrer-Policy` header, it seems to be possible to include this into the CSP header like `Content-Security-Policy: referrer no-referrer;`. Security headers are fun but I don't want to push out everything that exists :P And since one needs a CSP header anyway, it would reduce the amount of different headers if the referrer policy is included there.

Unfortunately one looses 5 points when not sending `Referrer-Policy` anymore 😱 So I propose honoring this the same way it is done with `X-Frame-Options +5 X-Frame-Options (XFO) implemented via the CSP frame-ancestors directive` 😉

**Comment by exploide** [comment]
Ok, while I thought this was a good idea, it seems CSP referrer option is deprecated https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/referrer

Sorry and never mind.

**Comment by april** [comment]
No problem, but I appreciate where your head is at, and look forward to another sweet ideas.  :)
