### ISSUE TITLE
python3-dev Python.h required

### ISSUE THREAD

**Issue by gene1wood** [mozilla/http-observatory#321]
Some of the required modules depend on the system having the python development resources installed (e.g. in Ubuntu `sudo apt install python3-dev`). You may want to add this to the [prerequisites](https://github.com/mozilla/http-observatory#prerequisites).

**Comment by floatingatoll** [comment]
The only place I could see in the codebase that could interact with the
system packaging (as opposed to Python modules) is the Dockerfile.

Did you encounter an issue where the Docker wouldn’t build as specified
without python-dev?

If not, I didn’t see anywhere in the codebase designed to interact with
system-level package managers; where might such a dependency go?

**Comment by gene1wood** [comment]
Ah sorry, when I said prerequisites I meant the [section in the docs](https://github.com/mozilla/http-observatory#prerequisites)

**Comment by floatingatoll** [comment]
@gene1wood Does #333 work for you here?

**Comment by gene1wood** [comment]
Looks good
