### ISSUE TITLE
Score penalty for <script, <style src="//

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/http-observatory#324]
Hi, I'd like to request a score penalty for `<script src="//` and `<style src="//`. Per discussion elsewhere, it turns out that it's no longer good practice to use this form of protocol-variant link to avoid mixed-content warnings, as it can cause HTTPS webpages mistakenly served over HTTP to fetch external resources (such as `jquery.js`) over HTTP (or file!) instead. I can provide supporting evidence (privately) if needed explaining why I think this check should occur against Mozilla properties, at the very least.

**Comment by Nightfirecat** [comment]
[Relevant Paul Irish blog post on the topic]https://www.paulirish.com/2010/the-protocol-relative-url/), and an added disclaimer he edited in after some time (copied below for visibility):

> Update 2014.12.17:
> 
> Now that SSL is [encouraged for everyone](https://www.eff.org/encrypt-the-web-report) and [doesn’t have performance concerns](https://istlsfastyet.com/), this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the `https://` asset.
> 
> Allowing the snippet to request over HTTP opens the door for attacks like the [recent Github Man-on-the-side attack](http://www.netresec.com/?page=Blog&month=2015-03&post=China%27s-Man-on-the-Side-Attack-on-GitHub). It’s always safe to request HTTPS assets even if your site is on HTTP, however the reverse [is not true](https://developer.mozilla.org/en-US/docs/Security/MixedContent/How_to_fix_website_with_mixed_content).
> 
> More guidance and details in [Eric Mills’ guide to CDNs & HTTPS](https://github.com/konklone/cdns-to-https#conclusion-cdns-should-redirect-to-https) and [digitalgov.gov’s writeup on secure analytics hosting](https://www.digitalgov.gov/2015/08/14/secure-central-hosting-for-the-digital-analytics-program/).

**Comment by floatingatoll** [comment]
This one is entirely thanks to @gene1wood, I'm just the messenger :)

**Comment by floatingatoll** [comment]
#327 merged!
