### ISSUE TITLE
Is a score penalty appropriate for non-samesite X-XSS-Protection report URLs?

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/http-observatory#325]
Chromium https://bugs.chromium.org/p/chromium/issues/detail?id=441275 and https://bugs.chromium.org/p/chromium/issues/detail?id=807304 discuss Chrome's recent changes to `X-XSS-Protection`'s reporting URL, mandating that reports be sent to the same-site only.

Is this a widely agreed-upon approach to securing XXP reports? Should Observatory offer a +0 warning (or -X penalty!) when an XXP header is configured with a non-samesite reporting endpoint?

**Comment by april** [comment]
I don't think I've ever seen a site use XXSSP's reporting mechanism. I don't know if it's worth the time to code it until it's actually in use.
