### ISSUE TITLE
Site does not support HTTPS (it does) 

### ISSUE THREAD

**Issue by Razerwire** [mozilla/http-observatory#331]
Hi April,

First of I don't know whether to post this here or in the Repo of TLS-Observatory. 

The problem lies in scanning [www.bonnieradvocaten.nl](https://www.bonnieradvocaten.nl ) on the TLS-observatory tab it'll show:
[Site does not support HTTPS](https://observatory.mozilla.org/analyze/www.bonnieradvocaten.nl&third-party=false#tls)
This site really does support HTTPS and is in fact only reachable via HTTPS  (redirect chain to HTTPS and domain utilizes  HSTS preloading). 

This site recently switched to a Comodo-EV cert using 4096-bit RSA (don't know if there's a connection there.
The certificate chain is in order: 
[SSLabs scan for wwww.bonnieradvocaten.nl](https://www.ssllabs.com/ssltest/analyze.html?d=www.bonnieradvocaten.nl&latest ).

If you need more details regarding web-server setup please PM-me.

Regards,
Razerwire

**Comment by floatingatoll** [comment]
The URL linked above says:

https://observatory.mozilla.org/analyze/www.bonnieradvocaten.nl&third-party=false

That ampersand `&` is invalid, as no question mark `?` has yet started a query arguments phase. The HTTP Observatory tab shows that the ampersand is being parsed as the hostname, so the TLS Observatory tab is probably trying to resolve a hostname with `&third-party=false` appended to it.

When I remove `&third-party=false` from the URL above, the TLS Observatory tab works correctly again. Do you know how this URL came to include that ampersand fragment?

**Comment by Razerwire** [comment]
I just entered "www.bonnieradvocaten.nl" > checked the box "Don't scan with third-party scanners" and pressed the "Enter / Return" key on my keyboard.

**Comment by floatingatoll** [comment]
Thanks! That's definitely a site frontend issue, then. Temporarily, you can uncheck that box to get valid TLS scan results, or you can change the & to ? in the URL in your browser, until the frontend bug mozilla/http-observatory-website#150 is fixed. The frontend lives in a different repository, so I'm closing this issue.
