### ISSUE TITLE
SRI edge case

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/http-observatory#337]
Hi, @april.

I have a use case where the SRI check fails.

On `bootstrapcdn.com`'s develop branch (https://dev.bootstrapcdn.com - we haven't deployed to production yet) I have the following situation:

1. no `script` tags
2. inline JS with `nonce`s
3. I'm loading via JS most of the JS files with the `integrity` attribute set

So, technically, the SRI check is right because it's only looking for `script` tags. But we do use SRI.

Not a big deal, but I wanted to bring it to your attention.

**Comment by floatingatoll** [comment]
Are you seeing a negative penalty for this scenario? What specific SRI
and/or script entries are shown in your site’s scoring report?

**Comment by XhmikosR** [comment]
I'm seeing -5 (Subresource Integrity (SRI) not implemented, but all external scripts are loaded over https) in the SRI test.

I looked into the code quite briefly and it seems the check only looks for `script` tags so this case isn't covered. :)

**Comment by april** [comment]
Hey there! I just got back, so I'll take a look into this.

**Comment by april** [comment]
It looks like it's loading this external script without SRI:

`https://cdn.carbonads.com/carbon.js?zoneid=1673&serve=C6AILKT&placement=bootstrapcdncom`

Does that look familiar to you?

**Comment by XhmikosR** [comment]
@april: yeah, a couple of 3rd-party scripts don't use SRI. The others do though.

BTW, I already deployed to production so you can check https://www.bootstrapcdn.com

**Comment by XhmikosR** [comment]
So basically the DOM is this:

```html
<script src="https://www.google-analytics.com/analytics.js"></script>
<script id="twitter-wjs" src="https://platform.twitter.com/widgets.js"></script>
<script src="/assets/js/vendor/clipboard.min.3f36881.js" integrity="sha384-5tfO0soa+FisnuBhaHP2VmPXQG/JZ8dLcRL43IkJFzbsXTXT6zIX8q8sIT0VSe2G" crossorigin="anonymous"></script>
<script src="/assets/js/main.e2eff36.js" integrity="sha384-bPbAgsg1m4D/D9QaiubvFXYhunpqVvao3nh1MGeMGn8gsizgOy52gj02eMEJwfef" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.bundle.min.js" integrity="sha384-lZmvU/TzxoIQIOD9yQDEpvxp6wEU32Fy0ckUgOH4EIlMOCdR823rg4+3gWRwnX1M" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8" async="" src="https://platform.twitter.com/js/button.4e380b7372da43f94df254b09037e839.js"></script>
<script type="text/javascript" charset="utf-8" async="" src="https://platform.twitter.com/js/timeline.16fd64cc2350cce575f82ca77ea6b11c.js"></script>
<script id="_carbonads_projs" type="text/javascript" src="//srv.carbonads.net/ads/C6AILKT.json?segment=placement:bootstrapcdncom&amp;callback=_carbonads_go"></script>
```

As you can see our JS and our CDN files do have SRI set .

**Comment by april** [comment]
Third-party scripts are the ones where it's most important (and most difficult) to have SRI set.  :)

**Comment by XhmikosR** [comment]
True, but hey, I wanted the CDN files covered because MaxCDN was hit by that some years ago ;)

**Comment by MestreLion** [comment]
Since this is still open, question: is there any tool can can pinpoint _which_ of my external resources are NOT being loaded with integrity check? Tests complain "Subresource Integrity (SRI) not implemented, but all external scripts are loaded over https", but I've triple-checked my sources and can't find any without integrity and crossorigin.

**Comment by floatingatoll** [comment]
It’s the one that says

src=//

Change that to

src=https://

In all cases where it’s used, and that may help.

**Comment by april** [comment]
Yep, exactly right. Just change the carbonads one to https and you should be good to go.

**Comment by XhmikosR** [comment]
@april: this issue isn't about the protocol relative question.

https://observatory.mozilla.org/analyze/www.bootstrapcdn.com

I do use SRI for jQuery, Bootstrap's JS and our JS yet this is not detected because I do it via JS.

**Comment by floatingatoll** [comment]
AFAIK Observatory doesn’t evaluate the effects of dynamic runtime-only
JavaScript when scoring websites, so I believe scoring will neither
evaluate nor reward/penalize the results of your post-load script activity.

**Comment by april** [comment]
Oh yeah, the Observatory doesn't run Selenium or any browsers or anything, due to the expense of that. As such, there is no way for it to detect run-time SRI. Sorry!
