### ISSUE TITLE
Question cookie scoring

### ISSUE THREAD

**Issue by martintko** [mozilla/http-observatory#338]
Hi there
I scanned a website that doesn't use any cookies at all with Mozilla Observatory.
The scan result is showing "No cookie detected". 
Why there is no passmark and some more + score points if there aren't any cookies?

**Comment by april** [comment]
There are a few tests like that. I mostly use positive points to reward to the use of new technologies and help with adoption. As time goes on, those positive points will go away and will transition to negative points for not using them.  :)
