### ISSUE TITLE
"This site's HSTS header does not meet current preloading requirements." 

### ISSUE THREAD

**Issue by Razerwire** [mozilla/http-observatory#342]
Hi,

I've just scanned https://www.bonnieradvocaten.nl and under the [third party tab ](https://observatory.mozilla.org/analyze/www.bonnieradvocaten.nl#third) more specifically under "hstspreload.org" the observatory notes the following:
"This site's HSTS header does not meet current preloading requirements." 

Yet AFAIK we're fully compliant and the tool at [hstspreload.org](https://hstspreload.org/?domain=bonnieradvocaten.nl) isn't reporting any problems.

So my guess is that this is a bug.

**Comment by april** [comment]
That's strange, I'll take a look at it on Monday. Sorry about the delay!

**Comment by april** [comment]
Scratch that, I just took at look at what the Observatory website is producing and it says:

`HSTS header continues to meet preloading requirements.`

So I wonder if it was a temporary bug on the hstspreload.org list? Or maybe you increased your `max-age`?

**Comment by Razerwire** [comment]
Hi April, 

I did not change the HSTS-header since September 2017. 

I've just tried it again and again the outcome is false:

![screenshot_2018-05-26_13-58-48](https://user-images.githubusercontent.com/14997009/40575879-afae24ec-60dc-11e8-801d-0a63fa4a2fa2.png)

**Comment by april** [comment]
Should be fixed now, thanks for letting me know!

**Comment by Razerwire** [comment]
Thanks for fixing it! And you're welcome!
