### ISSUE TITLE
Firefox shows an HPKP error but Observatory does not

### ISSUE THREAD

**Issue by hdatma** [mozilla/http-observatory#343]
Please sync the HPKP test with Firefox's own internal test, because FF 60.0.1 is showing its obscure HPKP error for pages that pass the observatory.

**Comment by april** [comment]
Can you provide a little more data on what you mean by obscure HPKP error?

**Comment by hdatma** [comment]
It is September 22, and I am unable to tell something that happened on May 24. I will re-open this ticket asap.
