### ISSUE TITLE
HSTS preloading not recognized

### ISSUE THREAD

**Issue by infosec-handbook** [mozilla/http-observatory#344]
When I scan `infosec-handbook.eu`, the HTTP Observatory shows "HTTP Strict Transport Security – HTTP Strict Transport Security (HSTS) header set to a minimum of six months (15768000)".

However, I expect "HTTP Strict Transport Security – Preloaded via the HTTP Strict Transport Security (HSTS) preloading process" since this website is listed on hstspreload.org for months, still meets preloading requirements and is also included in the [hsts-preload.json](https://raw.githubusercontent.com/mozilla/http-observatory/master/httpobs/conf/hsts-preload.json) file of this repo.

**Comment by april** [comment]
Yup, I've been working on updating a bunch of behind-the-scenes stuff, and so that change hasn't been pushed yet. Hopefully this week!

**Comment by april** [comment]
Aaaaand, fixed.  :)
