### ISSUE TITLE
Secure flag is showing set but we are still getting "cookie without secure flag" in zap report

### ISSUE THREAD

**Issue by alex2502** [mozilla/http-observatory#357]
Hi
secure flag is showing set in the Set-Cookie header but we are still getting "cookie without secure flag" in owasp zap report.

Please help.

Thanks in advance for your kind cooperation.

Regards
Amit

**Comment by floatingatoll** [comment]
On what site?

**Comment by alex2502** [comment]
I can not tell you the site name for Security reason.
If you can help me,please help me to solve this.

**Comment by april** [comment]
If you want to send me an email at april@mozilla.com with the site name, I'd be happy to take a look for you.

**Comment by alex2502** [comment]
This issue belongs to zap proxy.
By mistake,I raised in this group.
Sorry.
Thanks April and Floatingatoll for help.
