### ISSUE TITLE
Google recaptcha fails SRI

### ISSUE THREAD

**Issue by Tusky** [mozilla/http-observatory#364]
I have a site, which has SRI on every resource, except the google recaptcha js, which as far as I know cannot be implemented with SRI. But Observatory still gives it a -5 point rating, is there a way around this or is it planned to not count (but maybe just notify) it as a fail?

**Comment by floatingatoll** [comment]
There’s no way around that. The penalty is for the safety issue created by
using unhashed offsite JavaScript. Google is perhaps less risky than
others, but the risk itself remains no matter how trustworthy they are or
aren’t.
