### ISSUE TITLE
CSP only checks for headers

### ISSUE THREAD

**Issue by liamsomerville** [mozilla/http-observatory#366]
The Standard for CSP also allows for it to be a Meta tag, observatory doesn't appear to allow or account for this.

Wondered if checking for the meta tag would be an option.

**Comment by april** [comment]
It should check for a `<meta>` tag and header. Are you not seeing it look at the meta tags?

**Comment by april** [comment]
Here is the code where it checks both:

https://github.com/mozilla/http-observatory/blob/master/httpobs/scanner/analyzer/headers.py#L113

But if you can point me to a site where it's missing the meta tag, that would be great. Thanks!
