### ISSUE TITLE
scans done locally or using API to observatory?

### ISSUE THREAD

**Issue by daniejstriata** [mozilla/http-observatory#381]
I'm sorry. It is not clear from installing this if it is simply an interface using API calls to Observatory or if it is a local instance of Observatory where I can scan a host from my own IP. 

When I run a scan I see this output which made me think the scan is done from Mozilla observatory's infrastructure rather than my own:
`Retrieving: https://http-observatory.security.mozilla.org/api/v1/getScanResults?scan=10...29Results are cached from 20h26m47s ago; use -r to rescan.`

I would like to be able to scan sites that is locked down to the internet and I would not be able to use the usual Mozilla observatory infrastructure.

**Comment by floatingatoll** [comment]
“Local scanner” instructions are in the README a few paragraphs down from
the top. When following those (e.g. “httpobs-local-scan”) your scans will
be performed locally, so that you can scan private sites.
