### ISSUE TITLE
Running docker-compose up should work without error

### ISSUE THREAD

**Issue by chris-aeviator** [mozilla/http-observatory#384]
When running docker-compose up with the provided repository, I will get an error staing 

```
ERROR: for website  Cannot start service website: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"uwsgi\": executable file not found in $PATH": unknown

```

Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
Ubuntu 16.05

**Comment by HectorIX** [comment]
You should install uWSGI through pip first
`pip install uWSGI`

**Comment by Stephenthomas794** [comment]
Did you ever find the fix? @chris-aeviator

**Comment by chris-aeviator** [comment]
@Stephenthomas794 did you try installing ´uWSGI´ ? I believe I've been raising this issue only to express that the project should come up after running ´docker-compose up´ without any further steps (which is the reason on using docker images in the first place). Nonetheless I did not further use a self-deployed version of mozilla observatory

**Comment by Stephenthomas794** [comment]
@chris-aeviator I forgot to pip freeze uWSGI into my requirements file. And I see what you're saying: project should launch at docker-compose up. However, docker-compose build only builds and installs everything according to the Dockerfiles. Docker-compose up launches it, which is where uwsgi would be used/activated, and thus our error would happen.

**Comment by lemosluan** [comment]
> You should install uWSGI through pip first
> `pip install uWSGI`

In our case, we didn't list the uswgi in requirements.txt. So, the CMD command to up the container failed.

**Comment by chris-aeviator** [comment]
So will this be fixed finally ?

**Comment by gene1wood** [comment]
Is there a change that can be made in the codebase to address this? If there's a PR with a fix I can review and merge it.

**Comment by lemosluan** [comment]
> So will this be fixed finally ?
> […](#)
> Am 13.08.2021 um 21:28 schrieb Luan Lemos Almeida ***@***.***>: ﻿ You should install uWSGI through pip first pip install uWSGI In our case, we didn't list the uswgi in requirements.txt. So, the CMD command to up the container failed. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

I'm sorry. 
My trouble was in another application, but the same error related here. The google search brought me here.

**Comment by chris-aeviator** [comment]
From how I understand this discussion adding the `pip install` to the Dockerfile would be the fix or am I mistaken?

**Comment by LeoMcA** [comment]
Running `docker-compose up` has been fixed in the `next` branch
