### ISSUE TITLE
ImmuniWeb/htbridge.com - SSL Security Test 

### ISSUE THREAD

**Issue by HighTechBridge** [mozilla/http-observatory#388]
Hi,

SSL test of htbridge.com is not working in Third-party Tests.

API documentation is here: https://www.immuniweb.com/ssl/API_documentation.pdf
and here: https://www.immuniweb.com/ssl/#api

Major change is that we changed domain from htbridge.com to immuniweb.com

If you implemented API changes from >1y ago, domain change will solve rest.

Cheers,

**Comment by mozdevcontrib** [comment]
This appears fixed now.
