### ISSUE TITLE
Negative Content Security Policy test results vs. default policy 'none'

### ISSUE THREAD

**Issue by gsauthof** [mozilla/http-observatory#391]
Say you have the following Content Security Policy:

    default-src 'none' ; img-src 'self' ; form-action 'self' ; style-src 'self'

With that I currently get on observatory.mozilla.org passes for

    Deny by default, using default-src 'none'
    Blocks execution of inline JavaScript by not allowing 'unsafe-inline' inside script-src

and similar tests.

But I also get some failures (red Xs) for:

    Clickjacking protection, using frame-ancestors
    Restricts use of the <base> tag by using base-uri 'none', base-uri 'self', or specific origins

Why?

I mean the default also applies to those directives, doesn't it?

Thus, the above policy actually does protect against clickjacking and restricts use of the base tag.

And I thus would expect a pass for them, as well.

**Comment by floatingatoll** [comment]
IIRC default-src only applies to *-src directives, and base-uri does not
end in -src even though it takes similar arguments.

**Comment by gsauthof** [comment]
@floatingatoll you are right - the specification lists only *-src directives as being affected by default-src:

https://www.w3.org/TR/CSP2/#directive-default-src
