### ISSUE TITLE
https://http-observatory.security.mozilla.org/api/v1/ not available anymore..?

### ISSUE THREAD

**Issue by macosxgeek** [mozilla/http-observatory#397]
Hi,

I was just trying to scan one of the web sites we are maintaining but I'm keep getting:

observatory [ERROR] Error: ESOCKETTIMEDOUT

Every time I'm running observatory-cli.. 

I was also trying to access observatory API URL via browser but when I'm trying to open: https://http-observatory.security.mozilla.org/api/v1/ I'm getting 404 response.. 

Can I ask if API has new home? Or it's simply not available anymore?

**Comment by mozdevcontrib** [comment]
The address is :

https://observatory.mozilla.org/

Note: Anything above 125 is a "bonus" for using Set-Cookie with the SameSite & using SRI for any scripts loded via, e.g.  https://cdnjs.com or even your iwn site such as (using my own as an example, though mine is only for style as I use no script. Using Cloudflare, which I belive you use, workers are exceptional to set Http Headers. Best of luck to you! I noticed that at one point https://filterlists.com had a 30 rating, though now it's quite low due to insecure settings. If you feel you want any help at all, do ask, as I'm extremely familiar with/how to write worker scripts for every MIME type one can think of. Peace.

- intr0
Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by macosxgeek** [comment]
@mozdevcontrib 

I'm not sure if you did understand my question I'm afraid.. ;-)

So I did edit the main script and replaced the API endpoint with: https://observatory.mozilla.org/ per your recommendation.

Now I'm getting: 

`observatory [ERROR] 405 - "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"`

So I don't think it's the right address.. As for the rest of your answer (Note section) - To be honest I have no idea what you are talking about ;-) I'm not using any of the servers mentioned above.. 

Anyway - thank you for the answer.

**Comment by floatingatoll** [comment]
https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md#protocol-calls specifies that API endpoint, which does respond with "Welcome to the HTTP Observatory!" on `/` but 404s on `/api`, but I didn't test with a POST client.

**Comment by mozdevcontrib** [comment]
Hello again,

Excuse my tiredness, You asked about the API. See this: https://github.com/mozilla/http-observatory/issues/394#issuecomment-522121611

- intr0

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by floatingatoll** [comment]
@mozdevcontrib An issue force-negotiating TLSv1.3 only as you describe in issue 394 would have prevented both the reporter of this issue and I from receiving a 404 Not Found HTTP response, which they did and which I confirmed. Issue 394 is an independent issue unrelated to this one.

**Comment by mozdevcontrib** [comment]
It;s the CentOS server used that needs an update, which it still has not received. That's the reply from April I was thinking of when I linked my own issue. I definitely need to clarify my responses.

- intr0

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by floatingatoll** [comment]
The CentOS server update in issue 394 would provide TLS 1.3 support. If we were unable to negotiate a TLS connection as you indicated in that issue, we would be unable to receive HTTP responses over the TLS connection, as the negotiation would have failed before any HTTP request and response exchange could occur.

```
$ curl -v https://http-observatory.security.mozilla.org/api/v1/
*   Trying 52.70.226.198...
* TCP_NODELAY set
* Connected to http-observatory.security.mozilla.org (52.70.226.198) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
...
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
> GET /api/v1/ HTTP/1.1
> Host: http-observatory.security.mozilla.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 404 NOT FOUND
```

**Comment by mozdevcontrib** [comment]
That is true - for TLSv1.3. Why you are unable to conect to the API using TLSv1.2 I cannot answer. Ask April; she may take awhile to respond, but she will explain what is happining. Do you currently have a Content-Security-Policy in place? And if so, may I have a look at the settings? Thank-you.

- intr0

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by floatingatoll** [comment]
As shown above, I can reproduce the issue with `curl`, so "Do you have a CSP in place?" isn't applicable.

**Comment by mozdevcontrib** [comment]
t may be if you've certain settings in place. Ex: `connect-src`  may need to be set from 'self'' to 
https://http-observatory.security.mozilla.org/api/v1/ - I know of a case with Google's fonts that required `connect-src` to be set to Google's APIs.

**Comment by mozdevcontrib** [comment]
> I'm not sure if you did understand my question I'm afraid.. ;-)
> 
> So I did edit the main script and replaced the API endpoint with: https://observatory.mozilla.org/ per your recommendation.

You were absolutely correct. I've spent yet another night working instead of sleeping. My Apologies.

**Comment by mozdevcontrib** [comment]
> Or it's simply not available anymore?

Ask April. It may very well be temporarily down until either the CentOS server functions properly or they switch it out for a Debian 10 server.

**Comment by macosxgeek** [comment]
@april ! Help ! :-)

**Comment by mozdevcontrib** [comment]
> As shown above, I can reproduce the issue with `curl`, so "Do you have a CSP in place?" isn't applicable.

`curl --head htps://http-observatory.security.mozilla.org/api./v1`

`responds with HTTP/1.1 503 Service Unavailable: Back-end server is at capacity`
`Connection: keep-alive`

**Comment by april** [comment]
This has been fixed with a code update that prevents some DB-heavy queries from being run concurrently by the public.

**Comment by macosxgeek** [comment]
@april You are the star!

**Comment by mozdevcontrib** [comment]
> @april You are the star!

'Tis why I recommend you ask her. I'm happy your issue no longer exists. 😁
