### ISSUE TITLE
Stuck on "Loading results"

### ISSUE THREAD

**Issue by scrouet** [mozilla/http-observatory#404]
Hello,

Not sure it is the best channel to report my issue, but for one URL the scan is stuck on "Loading results" and I never get any other page/result. How can I investigate?

**Comment by april** [comment]
Oh shoot, sorry I missed this. Are you still having trouble? With which domain?

**Comment by scrouet** [comment]
Actually it seems it works fine again.
Thank you.

**Comment by vivek-kandhvar** [comment]
Same problem here. The results never load for my instance hosted on GCP. Anything I am missing?
