### ISSUE TITLE
Can I integrate this API with my own product?

### ISSUE THREAD

**Issue by wolffe** [mozilla/http-observatory#405]
Can I integrate this API with my own product?

Is it a stable product with active development? Will it be around one year from now?

**Comment by april** [comment]
It's been around for about 5 years now, and has been stable. You can use it with your own product provided the load isn't too heavy and provided you aggressively cache.

It's also easy to integrate into your own product should you choose.

**Comment by wolffe** [comment]
It's already done, but it's not public. I intend to run it every night for a site monitoring service. I might have 100 sites when I launch the product. I use cURL with forced TLS 1.3 and HTTP/2 for connection to your API.

I hope to have 1000 sites by the end of the year and retire next year with an awesome service :)

Does it sound acceptable? Every night?
