### ISSUE TITLE
Update RDS certificates before 2/5/2020

### ISSUE THREAD

**Issue by gene1wood** [mozilla/http-observatory#406]
Please update the RDS certificate in the `infosec-prod` AWS account in the `us-east-1` region for DB `http-observatory-db`

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

**Comment by april** [comment]
Updated certificates have been deployed to the repo, still need to deploy to production and update the database.
