### ISSUE TITLE
User-Agent to specify http-observatory

### ISSUE THREAD

**Issue by craigfrancis** [mozilla/http-observatory#408]
Can the `User-Agent` note the request is coming from the `http-observatory`, e.g.:

    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0 Mozilla/http-observatory"

---

Firefox currently has an issue that means that websites with an `<svg><use /></svg>`, need to specify `default-src "self"` ([bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1303364#c4), [example](https://craig.dev/misc/firefox/2019-11-11-svg-use/)).

At the moment I set `default-src "none"` for all browsers, but change it to `"self"` when the User-Agent string contains "Firefox/".

This means I loose 5 points, and get a warning on the results page.

---

The current User-Agent appears to be:

    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0"

Although this repository has this set to:

    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0"

https://github.com/mozilla/http-observatory/blob/master/httpobs/conf/httpobs.conf#L24

**Comment by april** [comment]
It should now look something like:

`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0 Observatory/72.0"`

:)

**Comment by craigfrancis** [comment]
Thanks April :-)

I assume this will be uploaded to the Live server at some point? no rush, just noting that the current requests show the older `Firefox/71.0` (from IPv6 `2620:101:8032:74::1:14`).

**Comment by april** [comment]
Yep! I'm out of the country at the moment, and so I plan to get this done sometime mid next week, around the 5th of February.  :)

**Comment by april** [comment]
This should be deployed, sorry for the delay. Does everything look good on your end?

**Comment by craigfrancis** [comment]
It does, thank you April... I'm back to 135 points :-)
