### ISSUE TITLE
Publish `httpobs` to PyPI for easy installation and to be used as a package

### ISSUE THREAD

**Issue by faheel** [mozilla/http-observatory#409]
It would be great if `httpobs` can be published to PyPI (like [`httpobs-cli`](https://pypi.org/project/httpobs-cli/)) as it would make it much easier for it to be installed and also be used as a package in other Python projects.

**Comment by tognee** [comment]
I found this package on PyPi, is it the official one?

https://pypi.org/project/httpobs/

**Comment by faheel** [comment]
Based on the maintainers listed on PyPI I believe it is the official one
