### ISSUE TITLE
Repeated scanning of non-existent paths.

### ISSUE THREAD

**Issue by mozdevcontrib** [mozilla/http-observatory#413]
The Observatory has been scanning the following paths:

`/crossdomain.xml`
`/clientaccesspolicy.xml`
`/contribute.json`

Using IP `2620:101:8030:74::1:14`
From ASN `AS36856 MOZILLA-MDC1 - Mozilla Corporation`
With UA `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0`

I understand that these paths *may* exist in some projects / websites. However, perhaps having a way to opt out of these (and potentially other paths for which I'm currently unaware) paths being scanned any time the Observatory scans a site/project would be a fair idea. Thank-you.

EDIT: Please see https://github.com/mozilla/http-observatory/issues/408#issue-520936319 re: UA for reference to an idea that would help us (project/site creators) in handling the scanning to which I referred above.

**Comment by april** [comment]
Is the scanning causing a traffic issue? It should be only 3 GET requests, and they are limited in how fast they can be scanned. Just trying to understand. Thanks!  :)

**Comment by mozdevcontrib** [comment]
It's not a traffic issue. It's a logging issue. I worked around it but in so doing certain malicious requests are also no longer being logged. I'm sure I can somehow further workaround it so that only the malicious requests get logged and those from the Observatory are left out. It'd be a simpler solution now that I'm thinking about it more. I appreciate your response. Thank-you.

~intr0 Ⓐ Sent from ProtonMail Professional

**Comment by april** [comment]
I'm going to start adding `Observatory` to the user agent as well, if you want to key off of that in your logging.  :)

Thanks for your feedback though, I super appreciate it!

**Comment by mozdevcontrib** [comment]
Thank-you for adding the `Observatory` string in the user agent; it is going to help tremendously!

~intr0 Ⓐ Sent from ProtonMail Professional
