### ISSUE TITLE
No way to grade pages that are not the homepage via API

### ISSUE THREAD

**Issue by afmars** [mozilla/http-observatory#416]
The homepage is only one of many pages on a site. It would be great if the API and Website accepted a `path` option like the local scanner does.

**Comment by mpurusottamc** [comment]
I am looking for something similar as well.

**Comment by floatingatoll** [comment]
This isn’t allowed on the public API as it could be used maliciously against other sites. You can stand up your own private API server and flip off the restriction, or use the local scanner without any API (see the README for details).
