### ISSUE TITLE
Why the grade result is not the same as SslLabs?

### ISSUE THREAD

**Issue by parhamPudding** [mozilla/http-observatory#420]
I use both Sslabs and http-observatory for the same domain. But I can see the grades are not the same.
For observatory, the grade is "F", and the same domain has a grade "C" in the SslLabs?

https://api.dev.ssllabs.com/api/v3/analyze?host=yousee.dk&publish=off&startNew=on&fromCache=off&ignoreMismatch=off

https://http-observatory.security.mozilla.org/api/v1/analyze?host=yousee.dk

**Comment by floatingatoll** [comment]
Those grades aren't comparable to each other at all. They're each grading something different. If you wish to improve your SSLLabs score, you'll need to make changes to the HTTPS SSL/TLS configuration of your web server. If you wish to improve your HTTP Observatory score, you'll need to make changes to the HTTP/HTTPS response headers returned by your web server and/or to the site's HTML content.

The SSLLabs "SSL Server Test" [scoring grade of C](https://www.ssllabs.com/ssltest/analyze.html?d=yousee.dk&hideResults=on) is evaluating the SSL/TLS security properties of your HTTPS server, but does not itself perform any HTTP/HTTPS request or response evaluation.

The HTTP Observatory [scoring grade of F](https://observatory.mozilla.org/analyze/yousee.dk) is evaluating the security practices of your website, as delivered over HTTP and/or HTTPS, evaluating the HTTP and HTML responses returned by your web server, but does not itself evaluate the SSL/TLS security properties of any HTTPS responses.

Additionally, to clarify in case you encounter this and wonder if it's comparable to SSLLabs (it isn't):

The TLS Observatory [score of ?](https://observatory.mozilla.org/analyze/yousee.dk#tls) evaluates the SSL/TLS security properties of your website against Mozilla's [Server Side TLS recommendations](https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations), but does not perform 'grading' of your site on an A-F scale and instead simply indicates if your configuration complies with any level of recommendation offered.
