### ISSUE TITLE
large number of scans stuck at pending/arborted

### ISSUE THREAD

**Issue by Klotzkopf** [mozilla/http-observatory#425]
It seems like a lot of scans are just stuck at state pending or aborted. 
They get stuck on "Awaiting scanner instance" on the website too.

Is the service having issues or is this on my end?

**Comment by jaylinski** [comment]
Is this still happening? Works fine for me...

**Comment by twirlse** [comment]
We have the same problem.
The only thing that helps is to queue rescan from UI
