### ISSUE TITLE
2 identical sites - http-https redirect detected on only one.

### ISSUE THREAD

**Issue by MarkHeddaeus** [mozilla/http-observatory#426]
We have 2 identical sites: portal.toplinegroup.com and meetmarket.toplinegroup.com.

They are ASP.Net sites in IIS 8.5 that both point to the same folder, which means that the HTTP-HTTPS redirection is done exactly the same (since it's done in the config file that is shared by both).

When we scan the sites using the public scanner, the "portal" site fails the redirect test but the "meetmarket" site does not.

The redirect settings were changed after the "portal" site was first scanned (within the last 24 hours), but before the "meetmarket" site was scanned.

Any idea why one would fail? Could it still be caching it even though "force a rescan" is checked?

**Comment by floatingatoll** [comment]
`http://portal` returns a 403 Forbidden, while `http://meetmarket` returns a 301 Moved Permanently; this is likely the cause of the discrepancy in results.

**Comment by MarkHeddaeus** [comment]
Thanks floatingatoll!

That pointed me in the right direction. 

The "portal" site was set to Require SSL, so any call to the HTTP site was blocked (and thus no redirect), but it guess the browser was automatically trying the https link so it seemed like it was working.
