### ISSUE TITLE
Installation issue due dependency error

### ISSUE THREAD

**Issue by whoot** [mozilla/http-observatory#434]
Hey,

I get an installation error due to the installation of *psycopg2* in *httpobs/database/requirements.txt*
I did the following:
```bash
# Install the HTTP Observatory
$ git clone https://github.com/mozilla/http-observatory.git
$ cd http-observatory
$ pip3 install --upgrade .
$ pip3 install --upgrade -r requirements.txt
```

and got the following error:
![grafik](https://user-images.githubusercontent.com/8066322/96711516-f966f700-139d-11eb-9f7d-1a95f01d3630.png)

Changing in *httpobs/database/requirements.txt*
```bash
psycopg2>=2.7,<2.8 --no-binary psycopg2
```
to
```bash
psycopg2>=2.8,<2.9 --no-binary psycopg2
```

and the installation is successful.

**Comment by madshaun1984** [comment]
I'm having this same issue, the suggested fix here is not working (same error).

**Comment by gene1wood** [comment]
The error is due to psycopg/psycopg2#854 which prevents [psycorpg2 versions less than `2.8.4` from working under Python 3.8](https://github.com/psycopg/psycopg2/issues/854#issuecomment-611791946)

If ou use Python 3.7, the error shouldn't occur

**Comment by LeoMcA** [comment]
I've upgraded our deps (and migrated to poetry) in https://github.com/mozilla/http-observatory/commit/481706d58bb7ece2c23fb701dc0a4a69fd0e6d69, which fixes this issue
