### ISSUE TITLE
Protocol-Relative Urls Considered Insecure

### ISSUE THREAD

**Issue by ray-novak** [mozilla/http-observatory#439]
The page is forced to use https, and the CSP includes upgrade-insecure-requests, and yet using a protocol-relative url costs me 45 subresource integrity points. Ouch. I have a lot of leftover // urls from back in the good old insecure days. I wonder if these are truly insecure for some reason I don't understand, or if the observatory could be modified to accept them as secure if the page forces them to be secure.

**Comment by floatingatoll** [comment]
There are certain attacks, yes. It’s recommended to update them all to
https:// as there are no longer mixed-mode warnings in browsers when an
http:// url loads https:// content.

**Comment by ray-novak** [comment]
ok - thanx. I do plan to update all those urls but it not going to be fun... I was hoping that since those urls are forced to be secure by the containing page and CSP, that I could get away with it for a while.

**Comment by floatingatoll** [comment]
It's definitely worth fixing them, but the CSP header *should* do the correct thing and protect users from any attack in the meantime.
