### ISSUE TITLE
TLS Observatory broken

### ISSUE THREAD

**Issue by nod0n** [mozilla/http-observatory#441]
1. try mozilla.org or github.com
2. click on the TLS Observatory tab
3. wait
4. continue to wait ;)

**Comment by gene1wood** [comment]
I've notified the team that operates the TLS observatory API (which the HTTP Observatory consumes) and they will be looking into it. Until that point the TLS Observatory tab won't work.

**Comment by g-k** [comment]
This is fixed now. Please retry your scan.

@gene1wood can you close this issue?

**Comment by gene1wood** [comment]
@g-k Looks good, thanks so much for fixing this!
