### ISSUE TITLE
Fails to detect a 301 redirect from HTTP to HTTPS

### ISSUE THREAD

**Issue by Seirdy** [mozilla/http-observatory#448]
`seirdy.one` and all ~~but one~~ of its subdomains redirect from HTTP to HTTPS with a 301 status code. This redirect is correctly detected by the [HSTS Preload list](https://hstspreload.org/?domain=seirdy.one), cURL, FF, Chromium, Webkit2GTK-based browsers, SSLLabs, and others.

The Observatory instance hosted on https://observatory.mozilla.org [fails](https://observatory.mozilla.org/analyze/seirdy.one) to detect this redirect; it fails the site on the redirection test and docks 20 points.

Expected behavior: `seirdy.one` and `www.seirdy.one` pass the Redirection test.

Actual behavior: `seirdy.one` and `www.seirdy.one` fail the Redirection test (-20).

**Comment by Seirdy** [comment]
Updating the Nginx configs to redirect all subdomains to HTTPS has not fixed the issue.

**Comment by floatingatoll** [comment]
Note that as of right now, neither "seirdy.one" nor "www.seirdy.one" redirect from HTTP to HTTPS:

```
* Connected to seirdy.one (2604:a880:4:1d0::18a:a000) port 80 (#0)
> GET / HTTP/1.1
> Host: seirdy.one

< HTTP/1.1 405 Method Not Allowed
```

**Comment by Seirdy** [comment]
That's odd. Here's my cURL output:

``` console
$ curl -v http://seirdy.one
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 143.110.224.186:80...
* Connected to seirdy.one (143.110.224.186) port 80 (#0)
> GET / HTTP/1.1
> Host: seirdy.one
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 23 Jun 2021 01:50:22 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: https://seirdy.one/
< 
{ [162 bytes data]

100   162  100   162    0     0   1820      0 --:--:-- --:--:-- --:--:--  1820
* Connection #0 to host seirdy.one left intact
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
$ curl -v http://www.seirdy.one
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 143.110.224.186:80...
* Connected to www.seirdy.one (143.110.224.186) port 80 (#0)
> GET / HTTP/1.1
> Host: www.seirdy.one
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 23 Jun 2021 01:50:38 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: https://seirdy.one/
< 
{ [162 bytes data]

100   162  100   162    0     0   1820      0 --:--:-- --:--:-- --:--:--  1820
* Connection #0 to host www.seirdy.one left intact
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by floatingatoll** [comment]
"seirdy.one" and "www.seirdy.one" have both IPv4 and IPv6 addresses. The
webserver at the IPv6 address is returning 405. The webserver at the IPv4
address is (correctly) returning 301. That may be the root of the issue
here.

**Comment by Seirdy** [comment]
Tested with `curl/7.76` and `curl/7.19.7`, linked against OpenSSL 1.1.1k FIPS and OpenSSL 1.0.1e-fips, respectively.

Also tested with `curl/7.77.0` linked against OpenSSL 1.1.1i on my Alpine box.

**Comment by Seirdy** [comment]
On Tue, Jun 22, 2021 at 06:55:44PM -0700, floatingatoll wrote:
>"seirdy.one" and "www.seirdy.one" have both IPv4 and IPv6 addresses. The
>webserver at the IPv6 address is returning 405. The webserver at the IPv4
>address is (correctly) returning 301. That may be the root of the issue
>here.

Oh, that explains it. Thanks!

**Comment by floatingatoll** [comment]
Sure thing!
