### ISSUE TITLE
Support running against localhost

### ISSUE THREAD

**Issue by steveworkman** [mozilla/http-observatory#65]
In order to test changes to cookie settings, CSP and other things quickly, it would be really good if the httpobs could be run against a localhost environment. At the moment, this doesnt work.

**Comment by marumari** [comment]
I'll likely make this a configurable option eventually, but you can comment this out on your local instance and things should work properly:

https://github.com/mozilla/http-observatory/blob/master/httpobs/scanner/utils.py#L25

**Comment by OmgImAlexis** [comment]
As a work around you should be able to use it with xip.io as they allow pointing to local ip addresses like http://0.0.0.0.xip.io for localhost.

**Comment by moustafak** [comment]
April, is there another command that needs to be run to propagate the changes? I commented out the block of code referenced but same result. I restarted ubuntu as well..

`httpobs localhost -v`

`Unable to get result from the HTTP Observatory. Error: localhost is an invalid hostname.
Retrieving: https://http-observatory.security.mozilla.org/api/v1/analyze?host=localhost`
