### ISSUE TITLE
Cannot specify a port for specific environment testing

### ISSUE THREAD

**Issue by steveworkman** [mozilla/http-observatory#66]
Some servers, especially a localhost environment, will be presenting content on a port other than 80 and 443.

It would be great to specify a port for httpobs to test against, for example, httpPort=8999&httpsPort=8443

**Comment by marumari** [comment]
I think this is something that will happen eventually, but it's likely to be disabled on our production instance, due to its possible use in mucking up all sorts of random servers on the internet.

**Comment by claudijd** [comment]
👍 very useful for local development if that was a thing

**Comment by marumari** [comment]
Hey there, @claudijd and @steveworkman!

This is now available in the local-only API version of this.  You can either use a CLI tool or you can call directly into the local scan function.  It works without a database and lets you scan whatever ports you would like.  I don't expect this to ever make it into the official public API, so I am going to close this out as fixed for now.

Do let me know if you have any troubles with the local scanning stuff at all.  Thanks!
