### ISSUE TITLE
Allow testing of local services as part of local development or CI

### ISSUE THREAD

**Issue by catlee** [mozilla/http-observatory#77]
I'd like to run the http observatory tests as part of our CI, but currently it's impossible to test services running on e.g. localhost:8080

**Comment by claudijd** [comment]
There is something like this happening with zap-cli where it's simply dockerized and then run locally.  Maybe that could we do the same approach with httpobs checks?  (ZAP-CLI Reference: https://blog.mozilla.org/webqa/2016/06/28/dockerized-owasp-zap-security-scanning-in-jenkins-part-two/)

**Comment by floatingatoll** [comment]
#158 implements a scan() function that can be used without invoking any of the server components, and it's working out well for us in Webops for scanning sites that are difficult to access with the public scanner. See #158 or README.md for more details on how invoking local scans for your CI.
