### ISSUE TITLE
Specify custom user agent upon scan

### ISSUE THREAD

**Issue by pwnbus** [mozilla/http-observatory#82]
Allow the ability for a user to either 1) select from a dropdown of different user agents ( aka mobile, IE, Firefox, chrome etc) or 2) having a text box to specify a specific one upon scan.

This way, the user can try and test out different versions of a website (mobile vs desktop for example).

**Comment by floatingatoll** [comment]
This implies a significant amount of UX and underlying data store support for "results per user-agent", if not already available.

**Comment by marumari** [comment]
Looking back on this, I think the best solution in this case is for people to download and run their own instance.  I think I'd rather put my time towards making that easier than doing a lot of rework to make this possible.

Thanks for reporting this, and hopefully I can make your desires easier.  It is currently just a value in a .conf file, if we can make running your own instance easy than we should be golden.
