### ISSUE TITLE
Filter potentially offensive site results

### ISSUE THREAD

**Issue by jeffbryner** [mozilla/http-observatory#90]
Though most scanning sites don't filter results from adult sites, etc. let's up the standard and screen what ends up by default on the home page for recent scans. 

Can likely use: 
https://github.com/mozilla/heatmap/tree/master/pornfilter

And have a go at filtering via hiding the result in: 
https://github.com/mozilla/http-observatory/blob/3f1e36a011beecf9f88cda42cf5956c2f80d7c27/httpobs/website/api.py#L46

**Comment by marumari** [comment]
Who is this @jeffbryner with all these fancy technical bugs?

**Comment by marumari** [comment]
Anyways, I should be able to automatically mark scans for these sites as "hidden" when they're submitted via the API.  Just load this file up when the server starts up, the same way as I do with the Chromium HSTS list.

**Comment by floatingatoll** [comment]
I think this was eventually fixed by hiding the list of recently-scanned sites by default, unless the user accepts the warning and expands it for viewing. Tentatively closing, but of course y'all can reopen if more work is desired.
