### ISSUE TITLE
Scanner seams to not check DNSSEC

### ISSUE THREAD

**Issue by tdelmas** [mozilla/http-observatory#95]
https://observatory.mozilla.org/analyze.html?host=www.dnssec-failed.org

**Comment by marumari** [comment]
Thanks for sending this in.  I have a similar bug here:

https://github.com/mozilla/http-observatory-website/issues/30

...that I closed out and gave an explanation on.  I really appreciate, though!

**Comment by tdelmas** [comment]
Thank you for the answer. Sorry I didn't thought about search for it in the other github repo!

>I don't even think any browsers support DNSSEC, so currently it is dead in the water for the web.

Just for information, at least Google public DNS check for DNSSEC: https://developers.google.com/speed/public-dns/faq#gdns_validation_failure

But I totally understand you (currently) classified it as out of scope for the http observatory ;)

**Comment by marumari** [comment]
Yeah, totally okay.  It's a bit confusing with three repos, but I didn't want them to get too muddled up together if I could avoid it.

I do really hope that we someday come up with a better solution than DNSSEC that will be easier to integrate into all sorts of toolchains.  :)
