### ISSUE TITLE
Issue quality badges

### ISSUE THREAD

**Issue by jvehent** [mozilla/http-observatory#96]
Sites should be able to list quality badges on their home or github pages. For example:

![observatory A](https://img.shields.io/badge/observatory-A%2B-brightgreen.svg)

![observatory F](https://img.shields.io/badge/observatory-F-red.svg)

**Comment by jeffbryner** [comment]
But.. https://observatory.mozilla.org/analyze.html?host=jeffbryner.com  (tldr: F). 

Also www.jeffbryner.com needs a three.js version of this badge.

**Comment by floatingatoll** [comment]
How frequently should the Observatory background-rescan a site when the 'letter grade' API endpoint is fetched?

#176 would restrict access to data older than 36 hours. Are letter grades exempt from that restriction?

**Comment by marumari** [comment]
It should just do a normal scan, I would think, without a forced rescan.  That is cached for 24 hours, which I think is fine.

**Comment by yvele** [comment]
I've made a [shield.io issue](https://github.com/badges/shields/issues/2912) with some examples including score and rating:

[![Mozilla Observatory](https://img.shields.io/badge/observatory-A+%20(115/110)-brightgreen.svg)](https://observatory.mozilla.org/analyze/github.com)

[![Mozilla Observatory](https://img.shields.io/badge/observatory-F%20(0/110)-red.svg)](https://observatory.mozilla.org/analyze/baidu.com)

**Comment by yvele** [comment]
The PR https://github.com/badges/shields/pull/2935 is quite ready to merge, is anyone here able to review it?

The badge will look like

  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-A+%20(115/110)-brightgreen.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-B%20(80/110)-green.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-C+%20(65/110)-yellow.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-D--%20(15/110)-orange.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-F%20(0/110)-red.svg)](https://observatory.mozilla.org/analyze/baidu.com)
 - [![Mozilla Observatory](https://img.shields.io/badge/observatory-pending-lightgrey.svg)](https://observatory.mozilla.org/analyze/github.com)
 - [![Mozilla Observatory](https://img.shields.io/badge/observatory-starting-lightgrey.svg)](https://observatory.mozilla.org/analyze/github.com)
 - [![Mozilla Observatory](https://img.shields.io/badge/observatory-running-lightgrey.svg)](https://observatory.mozilla.org/analyze/github.com)

Or using the grade only form
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-A+-brightgreen.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-B-green.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-C+-yellow.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-D---orange.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-F-red.svg)](https://observatory.mozilla.org/analyze/baidu.com)

**Comment by jeffbryner** [comment]
LGTM, @april what do you think?

**Comment by april** [comment]
These look great – you mind if I review them and merge early next week? Ping me again if I don't get around to it. I'm in the process of revamping the website and that's -almost- done.  :)

**Comment by yvele** [comment]
@april not sure that you saw that the PR is in an [external repository](https://github.com/badges/shields), not owned by mozzila 😉 

I think we can add you as a reviewer of https://github.com/badges/shields/pull/2935

**Comment by april** [comment]
Ahh, whoops! That works for me!  :)
