### ISSUE TITLE
Adding HttpOnly results in worse score

### ISSUE THREAD

**Issue by taladar** [mozilla/http-observatory#97]
[ -30] Session cookie set without using the HttpOnly flag

turns into

[ -40] Session cookie set without using the Secure flag or set over http

on otherwise unchanged server once the PHP-Option

session.cookie_httponly

is turned on.

I would have expected the score for using none of HTTPS, HttpOnly, Secure to be worse than (or equal to) the one for using HttpOnly but not the other two.

**Comment by marumari** [comment]
That is strange.  It should always give you the worst possible negative modifier, if you meet that modifier's criteria.  Can you set it back to the -30 value and provide me a URL to test with?

Thanks!

**Comment by taladar** [comment]
I set it back to the old setting, verified the problem still occurs and sent you the details via email (don't want the URL here publicly).

**Comment by marumari** [comment]
This should be live now, and I can confirm that is now grading the provided site correctly.

Thank you so much for reporting this issue, totally caught a whole in my tests.

**Comment by taladar** [comment]
Thank you for fixing the problem this quickly.

**Comment by marumari** [comment]
You're very welcome.  :)
